/*
	DZAI Configuration File
	
	Description: Contains all configurable settings of DZAI. Contains settings for debugging, customization of AI units, spawning, and loot.
	
	Last updated: 6:25 AM 6/17/2014
*/

diag_log "[DZAI] Reading DZAI configuration file.";

/*	DZAI Settings
--------------------------------------------------------------------------------------------------------------------*/	

//Enable or disable event logging to arma2oaserver.rpt. Debug level setting. 0: No debug output, 1: Basic Debug output, 2: Extended Debug output. (Default: 0)
//Debug output may help finding additional information about DZAI's background behavior. This output is helpful when asking for help regarding bugs or unexpected behaviors.
DZAI_debugLevel = 0;

//Frequency of server monitor update to RPT log in seconds. The monitor periodically reports number of max/current AI units and dynamically spawned triggers into RPT log. (Default: 300, 0 = Disable reporting)										
DZAI_monitorRate = 300;

//Enable or disable verification of classname tables used by DZAI. If invalid entries are found, they are removed and logged into the RPT log.
//If disabled, any invalid classnames will not be removed and clients may crash if AI bodies with invalid items are looted. Disable ONLY if a previous scan shows no invalid classnames (Default: true).										
DZAI_verifyTables = true;

//Enable to have server spawn in objects/buildings normally spawned clientside by DayZ's CfgTownGenerator. Prevents AI from walking/shooting through clutter and other objects. (Default: true)	
//If running DayZ Mod ("vanilla DayZ") or DayZ Overwatch, it is highly recommended to enable this option, as many added buildings are handled by the CfgTownGenerator. Not used with Epoch.							
DZAI_objPatch = true;

//Minimum seconds to pass until each dead AI body or destroyed vehicle can be cleaned up by DZAI's task scheduler. DZAI will not clean up a body/vehicle if there is a player close by (Default: 900).	
//Note: Other cleanup scripts might interfere by cleaning up dead AI bodies/vehicles!									
DZAI_cleanupDelay = 900;									


/*

	DZAI_modName value	|	Enables additional settings for...	|	Automatically detected by DZAI? (If Yes, editing DZAI_modName is not needed)
	--------------------------------------------------------------------------------------------------------------------
	""						Automatically detect mod 						N/A
	"default"				Force default settings							N/A
	"2017"					DayZ 2017/Namalsk 2017						No - Must set DZAI_modName = "2017" to enable additional settings.
	"epoch"					DayZ Epoch 									Yes - Adds bar currency to AI loot tables, AI skins, Epoch foods, replaces toolbelt items with Epoch versions.
	"overwatch"				DayZ Overwatch 								Yes - Adds Overwatch skins for AI.
	"huntinggrounds"		DayZ Hunting Grounds 						Yes - Enables additional static AI spawns for expanded Lingor map, AI skins, and backpacks.
	"unleashed"				DayZ Unleashed								Yes - Enables Unleashed static AI spawns and AI skins.
	
*/

//(Optional) In most cases this setting should be left unchanged. This setting should only be changed if DZAI is detecting the wrong DayZ mod automatically. (Default: "")
DZAI_modName = "epoch";


/*	AI Unit Settings
--------------------------------------------------------------------------------------------------------------------*/		

//Enhanced AI health system setting. 
//If enabled, AI units will use DayZ's 12,000 blood system, can be knocked unconscious and Tasered, and can self-bloodbag/morphine. If disabled, AI units will use default Arma 2 damage handling. (Default: true)
DZAI_useHealthSystem = true;

//Minimum and maximum AI blood level to spawn each unit with. Each individual unit will have a randomized blood level within this range. Upper limit: 12000 blood (Default: [10000,12000])
//Note: No effect if DZAI_useHealthSystem is false
DZAI_unitBloodLevel = [10000,12000];

//Amount of blood restored from a full self-heal. One-third of the total amount is restored 3 times every 3 seconds. Note: Applies to infantry-type AI units. (Default: 6000)
//Note: No effect if DZAI_useHealthSystem is false
DZAI_unitHealAmount = 6000;

//Below this blood level, AI may decide to heal themselves for amount specified by DZAI_unitHealAmount. Healing requires 9 seconds to fully complete and can be interrupted by knocking the unit unconscious. (Default: 5000)
//Note: No effect if DZAI_useHealthSystem is false
DZAI_lowBloodLevel = 2000;

//Enable or disable zombie attraction to AI weapon sounds. No effect if DZAI_zombieEnemy is set to false. Enabling this option may impact server performance as a script is run for each AI bullet fired.
//Note: AI cannot be attacked or damaged by zombies.(Default: false)		
DZAI_weaponNoise = false;

//If enabled, AI group will attempt to track down player responsible for killing a group member. Players with radios will be given text warnings if they are being pursued (Default: true)
DZAI_findKiller = true;	

//If normal probability check for spawning NVGs fails, then give AI temporary NVGs only if they are spawned with weapongrade 1 or higher (applies only during nighttime hours). Temporary NVGs are unlootable and will be removed at death (Default: false).									
DZAI_tempNVGs = false;	

//Amount of humanity to reward player for killing an AI unit (Default: 0)									
DZAI_humanityGain = 25;										

//If enabled, players with radios will be given text warnings if they are being pursued by AI groups. (Default: true)
DZAI_radioMsgs = true;

//If enabled, last surviving unit of a group will be granted slightly boosted skills. No effect if unit is spawned alone (Default: false)
DZAI_lastManStanding = true;


/*DZAI client-side addon settings. 
**NOTE**: These settings require the DZAI client-side addon to be installed to your mission pbo file in order to work.
--------------------------------------------------------------------------------------------------------------------*/	

//Enable to use client-side radio addon for radio messages instead of remote execution method. (Default: false)
DZAI_clientRadio = false;

//Enable or disable AI hostility to zombies. If enabled, AI units spawned by DZAI will attack nearby zombies. (Default: false)
DZAI_zombieEnemy = true;	

//Maximum distance (in meters) for AI group leader to detect zombies. Increasing range beyond default may negatively impact server performance. (Default: 150)							
DZAI_zDetectRange = 50;									


/*	Static AI Spawning Settings
--------------------------------------------------------------------------------------------------------------------*/	

//Enable or disable static AI spawns. If enabled, AI spawn points will be generated in cities, towns, and other predefined areas. Does not affect custom-defined spawns (Default: true).
DZAI_staticAI = false;

//Set minimum and maximum wait time in seconds to respawn an AI group after all units have been killed. Applies to both static AI and custom spawned AI (Default: Min 300, Max 600).									
DZAI_respawnTimeMin = 300;
DZAI_respawnTimeMax = 600;

//Time to allow spawned AI units to exist in seconds before being despawned when no players are present in a trigger area. Applies to both static AI and custom spawned AI (Default: 120)										
DZAI_despawnWait = 120;										

//Respawn limits. Set to -1 for unlimited respawns. (Default: -1 for each).
DZAI_respawnLimit0 = -1; //Respawn limit for low level AI found in low-value areas (Default: -1)
DZAI_respawnLimit1 = -1; //Respawn limit for mid level AI found in cities and other mid-value areas (Default: -1)
DZAI_respawnLimit2 = -1; //Respawn limit for high level AI found in places with military loot (Default: -1)
DZAI_respawnLimit3 = -1; //Respawn limit for very high level AI in places with high-grade military loot (Default: -1)


/*	Dynamic AI Spawning Settings
--------------------------------------------------------------------------------------------------------------------*/		

//Enable or disable dynamic AI spawns. If enabled, AI spawn locations will be generated for randomly selected players at randomized intervals (Default: true)									
DZAI_dynAISpawns = false;

//Time (seconds) required to reach maximum spawn probability per player, after which the probability is reset to 0%. Lower number = More frequent spawns, Higher Number = Less frequent. (Recommended range: 1200-2700, Default: 1800)
DZAI_maxSpawnTime = 1800;

//Time (seconds) to allow each player to retain maximum spawn probability. (Default: 1800).
DZAI_keepMaxSpawnTime = 1800;

//Probability for dynamic AI to actively hunt a targeted player. If probability check fails, dynamic AI will patrol the area instead of hunting (Default: 0.50)
DZAI_huntingChance = 0.50;

//Probability to send first available AI helicopter to reinforce dynamic AI group. No effect if DZAI_maxHeliPatrols is set to zero. (Default: 0.50)
DZAI_heliReinforceChance = 0.50;

//Array of area blacklist markers. Players within marker areas will not be targeted for dynamic AI spawns (Example: ["BlacklistArea1","BlacklistArea2","BlacklistArea3"])
//Epoch: DZAI will automatically set up 200m-radius blacklist areas around each trader area.
DZAI_dynAreaBlacklist = [];

//Time to wait before despawning all AI units in dynamic trigger area when no players are present. (Default: 120)
DZAI_dynDespawnWait = 120;

//Enable or disable dynamic spawn-free zones of 600m radius around player spawn areas. (Default: false)
DZAI_freshSpawnSafeArea = false;


/*	AI Air vehicle patrol settings. These AI vehicles will randomly travel between different cities and towns.
--------------------------------------------------------------------------------------------------------------------*/		

//Global maximum number of active AI air vehicle patrols. Set at 0 to disable (Default: 0).							
DZAI_maxHeliPatrols = 0;

//Set minimum and maximum wait time in seconds to respawn an AI vehicle patrol after vehicle is destroyed or disabled. (Default: Min 600, Max 900).
DZAI_respawnTMinA = 600;
DZAI_respawnTMaxA = 900;

//Classnames of air vehicle types to use, with the maximum amount of each type to spawn. Default: [["UH1H_DZ",1]]
DZAI_heliList = [["UH1H_DZ",1]];

//Difficulty level of air vehicle patrol units. Difficulty level also affects unit loadout and loot. Possible values: 0 to 3 (Default: 3)
DZAI_heliUnitLevel = 3;

//Maximum number of gunner units per air vehicle. Limited by actual number of available gunner positions. (Default: 2)
DZAI_heliGunnerUnits = 3;

//Specify vehicle weapon for air vehicles that are unarmed by default. DZAI will arm these air vehicles with the specified weapons upon spawning each vehicle.
//Weapon classnames are verified. If the classname is invalid (banned or nonexistent), it will not be added to the vehicle.
//Format: Each row containing a vehicle classname will be equipped with the weapon from the corresponding row in weapon classnames section. DZAI will automatically select ammo type.
DZAI_airWeapons = [
	//Air vehicle classnames (Remember: no comma for last entry! Otherwise, separate each string with commas)
	["Helicopter1_Example_Classname","Helicopter2_Example_Classname"]
	,
	//Corresponding weapon classnames (Remember: no comma for last entry! Otherwise, separate each string with commas)
	["Helicopter1_Example_Weapon","Helicopter2_Example_Weapon"]
];


/*AI Land vehicle patrol settings. These AI vehicles will randomly travel between different cities and towns.
--------------------------------------------------------------------------------------------------------------------*/	

//Global maximum number of active AI land vehicle patrols. Set at 0 to disable (Default: 0).	
DZAI_maxLandPatrols = 3;

//Set minimum and maximum wait time in seconds to respawn an AI vehicle patrol after vehicle is destroyed or disabled. (Default: Min 600, Max 900).
DZAI_respawnTMinL = 600;
DZAI_respawnTMaxL = 900;

//Classnames of land vehicle types to use, with the maximum amount of each type to spawn. Default: [["UAZ_Unarmed_TK_EP1",1]]
DZAI_vehList = [["UAZ_MG_INS",1],["Offroad_DSHKM_Ins",1],["Pickup_PK_INS",1],["BMP2_HQ_INS",1],["BRDM2_INS",1],["UralOpen_INS",1],["Ural_INS",1],["BTR40_MG_TK_INS_EP1",1],["BTR40_TK_INS_EP1",1],["Ikarus_TK_CIV_EP1",1]];


//Difficulty level of land vehicle patrol units. Difficulty level also affects unit loadout and loot. Possible values: 0 to 3 (Default: 3)
DZAI_vehUnitLevel = 3;

//Maximum number of gunner units per land vehicle. Limited by actual number of available gunner positions. (Default: 1)
DZAI_vehGunnerUnits = 2;

//Maximum number of cargo units per land vehicle. Limited by actual number of available cargo positions. (Default: 3)
DZAI_vehCargoUnits = 20;


/*	AI Vehicle (Air & Land) Settings
--------------------------------------------------------------------------------------------------------------------*/

//Array of area blacklist markers. Areas covered by marker will not be used as waypoints for vehicle patrols. (Example: ["BlacklistArea1","BlacklistArea2","BlacklistArea3"])
//Note: Vehicles may still pass through these areas but will not make stops unless enemies are encountered.
DZAI_waypointBlacklist = [];


/*	AI weapon selection settings
--------------------------------------------------------------------------------------------------------------------*/

//True: Dynamically generate AI weapon list from CfgBuildingLoot (DayZ loot tables). False: Use preset weapon tables located near the end of this file. (Default: true).
//Highly recommended to enable DZAI_verifyTables if this option is set to false. 
DZAI_dynamicWeaponList = false;

//Determines whether DZAI reads from default DayZ loot tables for dynamic AI weapon generation or from user-installed custom loot tables. (Default: false)
//No effect if DZAI_dynamicWeaponList is 'false'. If DZAI is unable to find custom loot tables installed, default loot tables will be used instead. If no loot tables are found, DZAI will use prebuilt weapon tables.
DZAI_customLootTables = false;

//List of classnames of weapons that AI should never use. By default, AI may carry any lootable weapon. (Only if DZAI_dynamicWeaponList = true)  
//Example: DZAI_banAIWeapons = ["M107_DZ","BAF_AS50_scoped"] will remove the M107 and AS50 from AI weapon tables if dynamic weapon list is enabled.								
//Note: It is recommended to add all melee weapon classnames into this list as AI have issues using melee weapons. 
//Pre-banned weapons by DZAI: "Crossbow_DZ","Crossbow","MeleeHatchet","MeleeCrowbar","MeleeMachete","MeleeBaseball","MeleeBaseBallBat","MeleeBaseBallBatBarbed","MeleeBaseBallBatNails"
DZAI_banAIWeapons = [];										

//List of launcher-type weapons for mid/high-level AI to use (by default, weapongrade 1/2/3), example: ["M136"]. If left empty, AI will not use launcher weapons. (Default: [])
//If AI encounter an armored player vehicle, they will switch to a randomly-selected launcher-type weapon to engage.
//Weapon classnames added here are verified if DZAI_verifyTables is set to true. Note: Launcher weapons are removed from the AI unit upon death.
DZAI_launcherTypes = [];	

//List of AI weapongrades that are permitted to use launcher-type weapons. Individual custom weapongrade levels may be added to allow launcher use (Default: [1,2,3])
DZAI_launcherLevels = [1,2,3];								

//Limit of number of launcher-type weapons to add to each AI group. Groups cannot have more launcher weapons than their weapongrade value (Default: 1).
DZAI_launchersPerGroup = 1;


/*	AI loot quantity settings
--------------------------------------------------------------------------------------------------------------------*/

//Number of selections of medical items (Inventory)
DZAI_invmedicals = 1;

//Number of selections of edible items (Inventory) 										
DZAI_invedibles = 1;	

//Number of selections of medical items (Backpack)									
DZAI_bpmedicals = 1; 	

//Number of selections of edible items (Backpack)									
DZAI_bpedibles = 1;	

//Maximum number of items to select from DZAI_MiscItemS table.										
DZAI_numMiscItemS = 3;						

//Maximum number of items to select from DZAI_MiscItemL table.				
DZAI_numMiscItemL = 1;										


/*	AI loot probability settings
--------------------------------------------------------------------------------------------------------------------*/

//Chance to add each medical item.
DZAI_chanceMedicals = 0.70;	

//Chance to add each edible item.								
DZAI_chanceEdibles = 0.70;

//Chance to add each random item from DZAI_MiscItemS table.									
DZAI_chanceMiscItemS = 0.60;

//Chance to add each random item from DZAI_MiscItemL table.								
DZAI_chanceMiscItemL = 0.15;								


/*AI weapon/skill probabilities (gradeChances should add up to 1.00) - [Civilian, Military, MilitarySpecial, HeliCrash] - Note: AI with higher grade weaponry will also have higher skill settings.
--------------------------------------------------------------------------------------------------------------------*/

//equipType level 0 - most AI will have basic pistols or rifles, and occasionally common military weapons.
DZAI_gradeChances0 = [0.90,0.10,0.00,0.00];	

//equipType level 1 - most AI will have common rifles, many will have common military weapons. Very rarely, AI will spawn with high-grade military or helicrash weapons.				
DZAI_gradeChances1 = [0.65,0.30,0.04,0.01];	

//equipType level 2 - most AI carry military weapons, and occasionally high-grade military weapons.				
DZAI_gradeChances2 = [0.15,0.65,0.15,0.05];

//equipType level 3 - All AI will carry at least a military-grade weapon. Many will be carrying high-grade military weapons. Note: Air and land vehicle patrols use equipType level 3.					
DZAI_gradeChances3 = [0.00,0.50,0.35,0.15];	

//equipType level "dynamic" - Weapongrade chances for dynamic-spawned AI. Majority of dynamic AI will be carrying low-grade military weapons, some will carry high-grade military.			
DZAI_gradeChancesDyn = [0.00,0.88,0.09,0.03];				


/*
	AI skill settings
	Skill Level: Description
	0-1: Low to medium-skilled AI. Most common type of AI encountered. Intended to challenge players.
	2-3: High-skilled AI. Uncommon/rare type of AI found in places with military loot. Intended to kill players.
	Hint: The best way to quickly adjust AI difficulty is by modifying aimingAccuracy value. For all skill types, higher number = better skill.
*/

//AI skill settings level 0 (Skill, Minimum skill, Maximum skill). Baseline skill level: 0.50
DZAI_skill0 = [	
	["aimingAccuracy",0.10,0.125],
	["aimingShake",0.50,0.59],
	["aimingSpeed",0.50,0.59],
	["endurance",0.50,0.59],
	["spotDistance",0.50,0.59],
	["spotTime",0.50,0.59],
	["courage",0.50,0.59],
	["reloadSpeed",0.50,0.59],
	["commanding",0.60,0.69],
	["general",0.60,0.69]
];

//AI skill settings level 1 (Skill, Minimum skill, Maximum skill). Baseline skill level: 0.60
DZAI_skill1 = [	
	["aimingAccuracy",0.125,0.15],
	["aimingShake",0.60,0.69],
	["aimingSpeed",0.60,0.69],
	["endurance",0.60,0.69],
	["spotDistance",0.60,0.69],
	["spotTime",0.60,0.69],
	["courage",0.60,0.69],
	["reloadSpeed",0.60,0.69],
	["commanding",0.70,0.79],
	["general",0.70,0.79]
];

//AI skill settings level 2 (Skill, Minimum skill, Maximum skill). Baseline skill level: 0.70
DZAI_skill2 = [	
	["aimingAccuracy",0.175,0.225],
	["aimingShake",0.70,0.79],
	["aimingSpeed",0.70,0.79],
	["endurance",0.70,0.79],
	["spotDistance",0.70,0.79],
	["spotTime",0.70,0.79],
	["courage",0.70,0.79],
	["reloadSpeed",0.70,0.79],
	["commanding",0.80,0.89],
	["general",0.80,0.89]
];

//AI skill settings level 3 (Skill, Minimum skill, Maximum skill). Baseline skill level: 0.80
DZAI_skill3 = [	
	["aimingAccuracy",0.225,0.250],
	["aimingShake",0.80,0.89],
	["aimingSpeed",0.80,0.89],
	["endurance",0.80,0.89],
	["spotDistance",0.80,0.89],
	["spotTime",0.80,0.89],
	["courage",0.80,0.89],
	["reloadSpeed",0.80,0.89],
	["commanding",0.90,0.99],
	["general",0.90,0.99]
];


/*
	Additional AI skill settings can be defined (DZAI_skill4 - DZAI_skill9) for the corresponding custom weapongrade level using the same format above.
	Note: If a custom weapongrade is used without defining the corresponding custom skill settings, DZAI_skill3 settings will be used instead.
	Instructions: replace "nil" with the skill array. Refer to the above preset skill arrays for examples.
	Custom AI skill settings can only be used with custom-defined spawns (spawns created using the DZAI_spawn function).
*/

//weapongrade 4 skills
DZAI_skill4 = nil; 

//weapongrade 5 skills
DZAI_skill5 = nil; 

//weapongrade 6 skills
DZAI_skill6 = nil; 

//weapongrade 7 skills
DZAI_skill7 = nil; 

//weapongrade 8 skills
DZAI_skill8 = nil;

//weapongrade 9 skills
DZAI_skill9 = nil; 


/*
	AI weapon, loot, and equipment settings
	
	DZAI will first load the classname tables defined below, the modify the settings according to the DayZ map/mod being run.
	
	Example: DZAI will always first load the classname tables defined below, then if DayZ Epoch is detected, DZAI will add or overwrite settings specified by \world_classname_configs\epoch\dayz_epoch.sqf. 
	
*/

//Default weapon classname tables - DZAI will ONLY use these tables if the dynamic weapon list (DZAI_dynamicWeaponList) is disabled, otherwise they are ignored and overwritten if it is enabled.
//Note: Low-level AI (weapongrade 0) may use pistols listed in DZAI_Pistols0 or DZAI_Pistols1. Mid/high level AI (weapongrade 1+) will carry pistol weapons but not use them - they will use rifle weapons instead.
//------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
DZAI_Pistols0 = ["RH_m93r"
,"RH_g18"
,"RH_mp5kp"
,"RH_mp7p"
,"RH_mac10p"
,"RH_tec9"
,"RH_muzi"
,"UZI_EP1"
,"UZI_SD_EP1"
,"RH_pp2000p"
,"Sa61_EP1"
,"RH_vz61"
,"RH_g17"
,"RH_m9"
,"RH_m9c"
,"RH_browninghp"
,"RH_anac"
,"RH_anacg"
,"RH_python"
,"RH_deagle"
,"RH_Deagleg"
,"RH_Deaglem"
,"RH_Deaglemzb"
,"RH_Deaglemz"
,"RH_Deagles"
,"LEXX_glock17_EP1_BLACK"
,"MCNO_glock17_EP1_WHITE"
,"glock17_EP1"
,"RH_g19"
,"RH_g19t"
,"RH_m1911"
,"Colt1911"
,"RH_m1911old"
,"M9"
,"RH_pm"
,"Makarov"
,"RH_mk22"
,"RH_mk22v"
,"RH_p38"
,"RH_ppk"
,"revolver_EP1"
,"revolver_gold_EP1"
,"RH_mk2"
,"RH_p226"
,"RH_p226s"
,"RH_aps"
,"RH_bull"
,"RH_tt33"
,"RH_usp"
,"RH_uspm"
,"RH_m9sd"
,"RH_m9csd"
,"RH_g17sd"
,"RH_m1911sd"
,"M9SD"
,"RH_pmsd"
,"MakarovSD"
,"RH_mk22sd"
,"RH_mk22vsd"
,"RH_apssd"
,"RH_uspsd"]; 				//Weapongrade 0 pistols
DZAI_Pistols1 = ["RH_m93r"
,"RH_g18"
,"RH_mp5kp"
,"RH_mp7p"
,"RH_mac10p"
,"RH_tec9"
,"RH_muzi"
,"UZI_EP1"
,"UZI_SD_EP1"
,"RH_pp2000p"
,"Sa61_EP1"
,"RH_vz61"
,"RH_g17"
,"RH_m9"
,"RH_m9c"
,"RH_browninghp"
,"RH_anac"
,"RH_anacg"
,"RH_python"
,"RH_deagle"
,"RH_Deagleg"
,"RH_Deaglem"
,"RH_Deaglemzb"
,"RH_Deaglemz"
,"RH_Deagles"
,"LEXX_glock17_EP1_BLACK"
,"MCNO_glock17_EP1_WHITE"
,"glock17_EP1"
,"RH_g19"
,"RH_g19t"
,"RH_m1911"
,"Colt1911"
,"RH_m1911old"
,"M9"
,"RH_pm"
,"Makarov"
,"RH_mk22"
,"RH_mk22v"
,"RH_p38"
,"RH_ppk"
,"revolver_EP1"
,"revolver_gold_EP1"
,"RH_mk2"
,"RH_p226"
,"RH_p226s"
,"RH_aps"
,"RH_bull"
,"RH_tt33"
,"RH_usp"
,"RH_uspm"
,"RH_m9sd"
,"RH_m9csd"
,"RH_g17sd"
,"RH_m1911sd"
,"M9SD"
,"RH_pmsd"
,"MakarovSD"
,"RH_mk22sd"
,"RH_mk22vsd"
,"RH_apssd"
,"RH_uspsd"]; 	//Weapongrade 1 pistols
DZAI_Pistols2 = ["RH_m93r"
,"RH_g18"
,"RH_mp5kp"
,"RH_mp7p"
,"RH_mac10p"
,"RH_tec9"
,"RH_muzi"
,"UZI_EP1"
,"UZI_SD_EP1"
,"RH_pp2000p"
,"Sa61_EP1"
,"RH_vz61"
,"RH_g17"
,"RH_m9"
,"RH_m9c"
,"RH_browninghp"
,"RH_anac"
,"RH_anacg"
,"RH_python"
,"RH_deagle"
,"RH_Deagleg"
,"RH_Deaglem"
,"RH_Deaglemzb"
,"RH_Deaglemz"
,"RH_Deagles"
,"LEXX_glock17_EP1_BLACK"
,"MCNO_glock17_EP1_WHITE"
,"glock17_EP1"
,"RH_g19"
,"RH_g19t"
,"RH_m1911"
,"Colt1911"
,"RH_m1911old"
,"M9"
,"RH_pm"
,"Makarov"
,"RH_mk22"
,"RH_mk22v"
,"RH_p38"
,"RH_ppk"
,"revolver_EP1"
,"revolver_gold_EP1"
,"RH_mk2"
,"RH_p226"
,"RH_p226s"
,"RH_aps"
,"RH_bull"
,"RH_tt33"
,"RH_usp"
,"RH_uspm"
,"RH_m9sd"
,"RH_m9csd"
,"RH_g17sd"
,"RH_m1911sd"
,"M9SD"
,"RH_pmsd"
,"MakarovSD"
,"RH_mk22sd"
,"RH_mk22vsd"
,"RH_apssd"
,"RH_uspsd"]; 		//Weapongrade 2 pistols
DZAI_Pistols3 = ["RH_m93r"
,"RH_g18"
,"RH_mp5kp"
,"RH_mp7p"
,"RH_mac10p"
,"RH_tec9"
,"RH_muzi"
,"UZI_EP1"
,"UZI_SD_EP1"
,"RH_pp2000p"
,"Sa61_EP1"
,"RH_vz61"
,"RH_g17"
,"RH_m9"
,"RH_m9c"
,"RH_browninghp"
,"RH_anac"
,"RH_anacg"
,"RH_python"
,"RH_deagle"
,"RH_Deagleg"
,"RH_Deaglem"
,"RH_Deaglemzb"
,"RH_Deaglemz"
,"RH_Deagles"
,"LEXX_glock17_EP1_BLACK"
,"MCNO_glock17_EP1_WHITE"
,"glock17_EP1"
,"RH_g19"
,"RH_g19t"
,"RH_m1911"
,"Colt1911"
,"RH_m1911old"
,"M9"
,"RH_pm"
,"Makarov"
,"RH_mk22"
,"RH_mk22v"
,"RH_p38"
,"RH_ppk"
,"revolver_EP1"
,"revolver_gold_EP1"
,"RH_mk2"
,"RH_p226"
,"RH_p226s"
,"RH_aps"
,"RH_bull"
,"RH_tt33"
,"RH_usp"
,"RH_uspm"
,"RH_m9sd"
,"RH_m9csd"
,"RH_g17sd"
,"RH_m1911sd"
,"M9SD"
,"RH_pmsd"
,"MakarovSD"
,"RH_mk22sd"
,"RH_mk22vsd"
,"RH_apssd"
,"RH_uspsd"]; 		//Weapongrade 3 pistols

DZAI_Rifles0 = ["Winchester1866"
,"AA12_PMC"
,"MR43"
,"M1014"
,"Remington870"
,"Remington870_lamp"
,"Saiga12K"
,"RH_acr"
,"RH_acracog"
,"RH_acraim"
,"RH_acrb"
,"RH_acrbacog"
,"RH_acrbaim"
,"RH_acrbeotech"
,"RH_acrbgl"
,"RH_acrbglacog"
,"RH_acrbglaim"
,"RH_acrbgleotech"
,"RH_acreotech"
,"RH_acrgl"
,"RH_acrglacog"
,"RH_acrglaim"
,"RH_acrgleotech"
,"RH_hk416"
,"RH_hk416acog"
,"RH_hk416aim"
,"RH_hk416eotech"
,"RH_hk416gl"
,"RH_hk416glacog"
,"RH_hk416glaim"
,"RH_hk416gleotech"
,"RH_hk416s"
,"RH_hk416sacog"
,"RH_hk416saim"
,"RH_hk416sd"
,"RH_hk416sdaim"
,"RH_hk416sdeotech"
,"RH_hk416sdgl"
,"RH_hk416sdglaim"
,"RH_hk416sdgleotech"
,"RH_hk416seotech"
,"RH_hk416sgl"
,"RH_hk416sglacog"
,"RH_hk416sglaim"
,"RH_hk416sgleotech"
,"RH_hk417"
,"RH_hk417acog"
,"RH_hk417aim"
,"RH_hk417eotech"
,"RH_hk417s"
,"RH_hk417sacog"
,"RH_hk417saim"
,"RH_hk417sd"
,"RH_hk417sdacog"
,"RH_hk417sdaim"
,"RH_hk417sdeotech"
,"RH_hk417seotech"
,"RH_hk417sgl"
,"RH_hk417sglacog"
,"RH_hk417sglaim"
,"RH_hk417sgleotech"
,"G36_C_SD_camo"
,"G36_C_SD_eotech"
,"G36a"
,"G36A_camo"
,"G36C"
,"G36C_camo"
,"G36K"
,"G36K_camo"
,"AK_107_GL_kobra"
,"AK_107_GL_pso"
,"AK_107_kobra"
,"AK_107_pso"
,"AK_47_M"
,"AK_47_S"
,"AK_74"
,"AK_74_GL"
,"AK_74_GL_kobra"
,"AKS_74"
,"AKS_74_kobra"
,"AKS_74_pso"
,"AKS_74_U"
,"AKS_74_UN_kobra"
,"AKS_GOLD"
,"RH_AK102"
,"RH_AK102GL"
,"RH_ak103"
,"RH_ak103gl"
,"RH_ak103k"
,"RH_ak103kgl"
,"RH_ak104"
,"RH_ak104_1p29"
,"RH_ak104gl"
,"RH_ak104k"
,"RH_ak104kgl"
,"RH_ak105"
,"RH_ak105gl"
,"RH_ak105k"
,"RH_ak105kgl"
,"RH_AK107"
,"RH_AK107gl"
,"RH_AK107k"
,"RH_AK107kgl"
,"RH_ak47"
,"RH_ak47gl"
,"RH_ak74"
,"RH_ak74gl"
,"RH_ak74k"
,"RH_ak74kgl"
,"RH_ak74m"
,"RH_ak74mgl"
,"RH_ak74mk"
,"RH_ak74mkgl"
,"RH_akm"
,"RH_akmgl"
,"RH_akms"
,"RH_akmssd"
,"RH_aks47"
,"RH_aks47b"
,"RH_aks47g"
,"RH_aks47s"
,"RH_aks74"
,"RH_aks74gl"
,"RH_aks74k"
,"RH_aks74kgl"
,"RH_aks74m"
,"RH_aks74mgl"
,"RH_aks74mgl1p29"
,"RH_aks74mk"
,"RH_aks74mkgl"
,"RH_aks74p"
,"RH_aks74pgl"
,"RH_aks74pk"
,"RH_aks74pkgl"
,"RH_aks74u"
,"RH_aks74uk"
,"RH_aks74upt"
,"RH_aks74uptk"
,"RH_aks74usd"
,"RH_aks74usdk"
,"RH_rk95"
,"RH_Rk95ag"
,"RH_Rk95aim"
,"RH_Rk95sd"
,"RH_Rk95sdag"
,"RH_Rk95sdaim"
,"Sa58P_EP1"
,"Sa58V_CCO_EP1"
,"Sa58V_EP1"
,"Sa58V_RCO_EP1"
,"BAF_L85A2_RIS_ACOG"
,"BAF_L85A2_RIS_CWS"
,"BAF_L85A2_RIS_Holo"
,"BAF_L85A2_RIS_SUSAT"
,"BAF_L85A2_UGL_ACOG"
,"BAF_L85A2_UGL_Holo"
,"BAF_L85A2_UGL_SUSAT"
,"ukf_L85A2"
,"ukf_L85A2_acog"
,"ukf_L85A2_acog_CQB"
,"ukf_L85A2_RIS"
,"ukf_L85A2_sd"
,"ukf_L85A2_sd_CQB"
,"ukf_L85A2_susat"
,"ukf_L85A2AG36"
,"ukf_L85A2AG36_acog"
,"ukf_L85A2AG36_acog_CQB"
,"ukf_L85A2AG36_acog_fgrip"
,"ukf_L85A2AG36_acog_fgrip_CQB"
,"ukf_L85A2AG36_fgrip"
,"ukf_L85A2AG36_sd"
,"ukf_L85A2AG36_sd_CQB"
,"ukf_L85A2AG36_sd_fgrip"
,"ukf_L85A2AG36_sd_fgrip_CQB"
,"ukf_L85A2AG36_susat"
,"ukf_L85A2AG36_susat_fgrip"
,"ukf_L85A2K_susat"
,"ukf_L86A2LSW"
,"ukf_L86A2LSW_fgrip"
,"ukf_L86A2LSW_susat"
,"ukf_L86A2LSW_susat_fgrip"
,"M4A1"
,"M4A1_Aim"
,"M4A1_Aim_camo"
,"M4A1_AIM_SD_camo"
,"M4A1_HWS_GL"
,"M4A1_HWS_GL_camo"
,"M4A1_HWS_GL_SD_Camo"
,"M4A1_RCO_GL"
,"M4A3_CCO_EP1"
,"M4A3_RCO_GL_EP1"
,"RH_M4"
,"RH_M4a1"
,"RH_M4a1acog"
,"RH_M4a1aim"
,"RH_M4a1eotech"
,"RH_M4a1gl"
,"RH_M4a1glacog"
,"RH_M4a1glaim"
,"RH_M4a1gleotech"
,"RH_M4a1r"
,"RH_M4acog"
,"RH_M4aim"
,"RH_M4aim_wdl"
,"RH_M4C"
,"RH_M4CACOG"
,"RH_M4CAIM"
,"RH_M4CEOTECH"
,"RH_M4CGL"
,"RH_M4CGLACOG"
,"RH_M4CGLAIM"
,"RH_M4CGLEOTECH"
,"RH_M4CMK"
,"RH_M4CMKACOG"
,"RH_M4CMKAIM"
,"RH_M4CMKEOTECH"
,"RH_M4CS"
,"RH_M4CSACOG"
,"RH_M4CSAIM"
,"RH_M4CSEOTECH"
,"RH_M4CT"
,"RH_M4CT_F"
,"RH_M4CTSD"
,"RH_M4CTSD_F"
,"RH_M4CTSDACOG"
,"RH_M4CTSDACOG_F"
,"RH_M4CTSDAIM"
,"RH_M4CTSDAIM_F"
,"RH_M4CTSDEOTECH"
,"RH_M4CTSDEOTECH_F"
,"RH_M4CTSDGL"
,"RH_M4CTSDGL_F"
,"RH_M4CTSDGLACOG"
,"RH_M4CTSDGLACOG_F"
,"RH_M4CTSDGLAIM"
,"RH_M4CTSDGLAIM_F"
,"RH_M4CTSDGLEOTECH"
,"RH_M4CTSDGLEOTECH_F"
,"RH_M4eotech"
,"RH_M4gl"
,"RH_M4glacog"
,"RH_M4glaim"
,"RH_M4gleotech"
,"RH_M4gleotech_wdl"
,"RH_M4m"
,"RH_M4macog"
,"RH_M4maim"
,"RH_M4meotech"
,"RH_M4r"
,"RH_M4sbr"
,"RH_M4sbracog"
,"RH_M4sbraim"
,"RH_M4sbreotech"
,"RH_M4sd"
,"RH_M4sdacog"
,"RH_M4sdaim"
,"RH_M4sdaim_wdl"
,"RH_M4sdeotech"
,"RH_M4sdgl"
,"RH_M4sdglacog"
,"RH_M4sdglaim"
,"RH_M4sdgleotech"
,"RH_M4sdgleotech_wdl"
,"m8_carbine"
,"m8_carbine_pmc"
,"m8_carbineGL"
,"m8_compact"
,"m8_compact_pmc"
,"m8_holo_sd"
,"m8_SAW"
,"RH_XM8"
,"RH_XM8C"
,"RH_XM8D"
,"RH_XM8DC"
,"RH_XM8DGL"
,"RH_XM8DSAW"
,"RH_XM8DSH"
,"RH_XM8GL"
,"RH_XM8SAW"
,"RH_XM8SH"
,"M16A2"
,"M16A2GL"
,"m16a4"
,"m16a4_acg"
,"M16A4_ACG_GL"
,"M16A4_GL"
,"RH_M16a1"
,"RH_M16a1gl"
,"RH_M16a1s"
,"RH_M16a1sgl"
,"RH_m16a2"
,"RH_m16a2aim"
,"RH_M16a2gl"
,"RH_M16a2glaim"
,"RH_M16a2s"
,"RH_M16a2sgl"
,"RH_M16a3"
,"RH_M16a3aim"
,"RH_M16a3c"
,"RH_M16a3cs"
,"RH_M16a3gl"
,"RH_M16a3s"
,"RH_M16a3sgl"
,"RH_M16a4"
,"RH_M16A4acog"
,"RH_M16A4aim"
,"RH_M16A4eotech"
,"RH_M16a4gl"
,"RH_M16A4glacog"
,"RH_M16A4glaim"
,"RH_M16A4gleotech"
,"RH_mas"
,"RH_masacog"
,"RH_masaim"
,"RH_masb"
,"RH_masbacog"
,"RH_masbaim"
,"RH_masbeotech"
,"RH_masbsd"
,"RH_masbsdacog"
,"RH_masbsdaim"
,"RH_masbsdeotech"
,"RH_maseotech"
,"RH_massd"
,"RH_massdacog"
,"RH_massdaim"
,"RH_massdeotech"
,"FN_FAL"
,"LeeEnfield"
,"RH_star21"
,"RH_an94"
,"RH_an94gl"
,"RH_ar10"
,"RH_ar10s"
,"RH_asval"
,"RH_asvalk"
,"RH_ctar21"
,"RH_ctar21glacog"
,"RH_ctar21m"
,"RH_ctar21mgl"
,"RH_Mk18"
,"RH_Mk18acog"
,"RH_Mk18aim"
,"RH_Mk18d"
,"RH_Mk18dacog"
,"RH_Mk18daim"
,"RH_mk18dc"
,"RH_mk18dcacog"
,"RH_mk18dcaim"
,"RH_mk18dceot"
,"RH_mk18dcgl"
,"RH_mk18dcglacog"
,"RH_mk18dcglaim"
,"RH_mk18dcgleot"
,"RH_mk18dcsd"
,"RH_mk18dcsdacog"
,"RH_mk18dcsdaim"
,"RH_mk18dcsdeot"
,"RH_Mk18deot"
,"RH_Mk18dgl"
,"RH_Mk18dglacog"
,"RH_Mk18dglaim"
,"RH_Mk18dgleot"
,"RH_Mk18dsd"
,"RH_Mk18dsdacog"
,"RH_Mk18dsdaim"
,"RH_Mk18dsdeot"
,"RH_Mk18eot"
,"RH_Mk18gl"
,"RH_Mk18glacog"
,"RH_Mk18glaim"
,"RH_Mk18gleot"
,"RH_Mk18sd"
,"RH_Mk18sdacog"
,"RH_Mk18sdaim"
,"RH_Mk18sdeot"
,"RH_Mk18t"
,"LEXX_SCAR_H_CQC_CCO_BLACK"
,"LEXX_SCAR_H_CQC_CCO_SD_BLACK"
,"LEXX_SCAR_H_STD_EGLM_Spect_BLACK"
,"LEXX_SCAR_L_CQC_BLACK"
,"LEXX_SCAR_L_CQC_CCO_SD_BLACK"
,"LEXX_SCAR_L_CQC_EGLM_Holo_BLACK"
,"LEXX_SCAR_L_CQC_Holo_BLACK"
,"LEXX_SCAR_L_STD_EGLM_RCO_BLACK"
,"LEXX_SCAR_L_STD_HOLO_BLACK"
,"LEXX_SCAR_L_STD_Mk4CQT_BLACK"
,"mcno_SCAR_H_CQC_CCO_SD_WHITE"
,"mcno_SCAR_H_CQC_CCO_WHITE"
,"mcno_SCAR_H_STD_EGLM_Spect_WHITE"
,"mcno_SCAR_L_CQC_CCO_SD_WHITE"
,"mcno_SCAR_L_CQC_EGLM_Holo_WHITE"
,"mcno_SCAR_L_CQC_Holo_WHITE"
,"mcno_SCAR_L_CQC_WHITE"
,"mcno_SCAR_L_STD_EGLM_RCO_WHITE"
,"mcno_SCAR_L_STD_HOLO_WHITE"
,"mcno_SCAR_L_STD_Mk4CQT_WHITE"
,"RH_SCARAK"
,"RH_SCARAKACOG"
,"RH_SCARAKAIM"
,"RH_SCARAKBAIM"
,"RH_SCARAKEOTECH"
,"RH_SCARH"
,"RH_SCARH_ACOG"
,"RH_SCARH_AIM"
,"RH_SCARH_EOTECH"
,"RH_SCARH_GL"
,"RH_SCARH_GL_ACOG"
,"RH_SCARH_GL_AIM"
,"RH_SCARH_GL_EOTECH"
,"RH_SCARH_GL_SPECTERDR"
,"RH_SCARH_MK4"
,"RH_SCARH_SD_ACOG"
,"RH_SCARH_SD_AIM"
,"RH_SCARH_SD_EOTECH"
,"RH_SCARH_SD_GL_AIM"
,"RH_SCARH_SD_GL_EOTECH"
,"RH_SCARH_SPECTERDR"
,"RH_SCARHB_EOTECH"
,"RH_SCARHB_GL_ACOG"
,"RH_SCARHB_SD_AIM"
,"RH_SCARHB_SD_GL_EOTECH"
,"RH_SCARL"
,"RH_SCARL_ACOG"
,"RH_SCARL_AIM"
,"RH_SCARL_DOC"
,"RH_SCARL_EOTECH"
,"RH_SCARL_GL"
,"RH_SCARL_GL_ACOG"
,"RH_SCARL_GL_AIM"
,"RH_SCARL_GL_EOTECH"
,"RH_SCARL_MK4"
,"RH_SCARL_SD_ACOG"
,"RH_SCARL_SD_AIM"
,"RH_SCARL_SD_DOC"
,"RH_SCARL_SD_EOTECH"
,"RH_SCARL_SD_GL_ACOG"
,"RH_SCARL_SD_GL_AIM"
,"RH_SCARL_SD_GL_EOTECH"
,"RH_SCARLB_AIM"
,"RH_SCARLB_GL_ACOG"
,"RH_SCARLB_SD_EOTECH"
,"RH_SCARLB_SD_GL_AIM"
,"SCAR_H_CQC_CCO"
,"SCAR_H_CQC_CCO_SD"
,"SCAR_H_STD_EGLM_Spect"
,"SCAR_L_CQC"
,"SCAR_L_CQC_CCO_SD"
,"SCAR_L_CQC_EGLM_Holo"
,"SCAR_L_CQC_Holo"
,"SCAR_L_STD_EGLM_RCO"
,"SCAR_L_STD_HOLO"
,"SCAR_L_STD_Mk4CQT"
,"RH_p90sdaim"
,"RH_p90sdeot"
,"RH_p90isd"
,"RH_mp5sd6aim"
,"RH_mp5sd6g"
,"RH_mp5sd6eot"
,"RH_mp5sd6RFX"
,"RH_mp7sdaim"
,"RH_mp7sdeot"
,"RH_umpsdaim"
,"RH_umpsdeot"
,"RH_umpsdRFX"
,"MP5SD"
,"RH_krisssdaim"
,"RH_krisssdeot"
,"RH_krisssdRFX"
,"RH_tmpsdaim"
,"RH_P90sd"
,"RH_mp5sd6"
,"RH_mp7sd"
,"RH_umpsd"
,"RH_krisssd"
,"RH_tmpsd"
,"RH_tmpsdeot"
,"RH_uzisd"
,"bizon_silenced"
,"RH_bizonsd"
,"RH_bizonsdk"
,"RH_P90aim"
,"RH_P90eot"
,"RH_P90i"
,"RH_HK53aim"
,"RH_HK53eot"
,"RH_HK53RFX"
,"RH_mp5a4aim"
,"RH_mp5a4eot"
,"RH_mp5a4RFX"
,"RH_mp5a5"
,"RH_mp5a5aim"
,"RH_mp5a5eodaim"
,"RH_mp5a5eodeot"
,"RH_mp5a5eodRFX"
,"RH_mp5a5eot"
,"RH_mp5a5eod"
,"RH_mp5a5RFX"
,"RH_mp5a5ris"
,"RH_mp5a5risaim"
,"RH_mp5a5riseot"
,"RH_mp5a5risRFX"
,"RH_mp5k"
,"RH_mp5kpdw"
,"RH_mp5kpdwaim"
,"RH_mp5kpdweot"
,"RH_mp5kpdwRFX"
,"RH_mp7aim"
,"RH_mp7eot"
,"RH_umpaim"
,"RH_umpRFX"
,"RH_bizon"
,"RH_bizonk"
,"bizon"
,"RH_P90"
,"RH_HK53"
,"RH_mp5a4"
,"RH_mp7"
,"RH_UMP"
,"RH_umpeot"
,"RH_mac10"
,"RH_PDR"
,"RH_pdraim"
,"RH_pdreot"
,"RH_PDW_AIM"
,"RH_PDW_EOTECH"
,"RH_krissaim"
,"RH_krisseot"
,"RH_krissRFX"
,"RH_tmpeot"
,"RH_uzig"
,"RH_uzim"
,"RH_pp2000"
,"RH_pp2000eot"
,"RH_PDW"
,"RH_PDW_ACOG"
,"RH_fmg9"
,"MP5A5"
,"RH_pp2000aim"
,"RH_tmp"
,"RH_kriss"
,"RH_tmpaim"
,"RH_uzi"
,"MIDF_Aug_A3"
,"MIDF_Aug_A3_acog"
,"MIDF_Aug_A3_acog_black"
,"MIDF_Aug_A3_acog_blue"
,"MIDF_Aug_A3_ACOG_GL"
,"MIDF_Aug_A3_ACOG_GL_BLACK"
,"MIDF_Aug_A3_ACOG_GL_BLUE"
,"MIDF_Aug_A3_Black"
,"MIDF_Aug_A3_Blue"
,"MIDF_Aug_A3_eotech"
,"MIDF_Aug_A3_eotech_black"
,"MIDF_Aug_A3_eotech_blue"
,"MIDF_Aug_A3_EOTECH_GL"
,"MIDF_Aug_A3_EOTECH_GL_BLACK"
,"MIDF_Aug_A3_EOTECH_GL_BLUE"
,"MIDF_Aug_A3_GL"
,"MIDF_Aug_A3_GL_black"
,"MIDF_Aug_A3_GL_blue"
,"M14_EP1"
,"RH_gr1"
,"RH_gr1sd"
,"RH_m14"
,"RH_m14acog"
,"RH_m14aim"
,"RH_M14EBR"
,"RH_M14EBR_SD"
,"RH_m14eot"
,"RH_m1s"
,"RH_m1sacog"
,"RH_m1saim"
,"RH_m1seot"
,"RH_m1sshd"
,"RH_m1st"
,"RH_m1stacog"
,"RH_m1staim"
,"RH_m1steot"
,"RH_m1stshd"
,"RH_m39emr"
,"RH_MK14"
,"RH_MK14ACOG"
,"RH_MK14AIM"
,"RH_mk14ebr"
,"RH_mk14ebr_sd"
,"RH_mk14ebrgc"
,"RH_mk14ebrgc_sd"
,"RH_MK14EOTECH"
,"RH_MK14SD"
,"RH_MK14SDACOG"
,"RH_MK14SDAIM"
,"RH_MK14SDEOTECH"
,"RH_mk14t"
,"RH_mk14tacog"
,"RH_mk14taim"
,"RH_mk14teot"
,"RH_mk14tsd"
,"RH_mk14tsdacog"
,"RH_mk14tsdaim"
,"RH_mk14tsdeot"
,"RH_oc14"
,"RH_oc14gl"
,"RH_oc14sd"
,"RH_sc2"
,"RH_sc2acog"
,"RH_sc2aim"
,"RH_sc2eot"
,"RH_sc2shd"
,"UKF_L115A3_fgrip"
,"UKF_L115A3_des"
,"UKF_L115A3_wdl_fgrip"
,"BAF_LRR_scoped"
,"UKF_L115A3_sd_fgrip"
,"UKF_L115A3_sd"
,"UKF_L115A3_sd_des"
,"UKF_L115A3_sd_des_fgrip"
,"UKF_L115A3_sd_wdl"
,"BAF_AS50_scoped_DZ"
,"BAF_LRR_scoped_W"
,"UKF_L115A3"
,"UKF_L115A3_des_fgrip"
,"UKF_L115A3_wdl"
,"UKF_L115A3_sd_wdl_fgrip"
,"m107_SKN"
,"USSR_cheytacM200_FDZ"
,"USSR_cheytacM200_sd_FDZ"
,"KSVK_DZE"
,"LEXX_SCAR_H_LNG_Sniper_SD_BLACK"
,"mcno_SCAR_H_LNG_Sniper_SD_WHITE"
,"RH_asvalsp"
,"RH_gr1sdsp"
,"RH_oc14sdsp"
,"RH_hk417sdsp"
,"RH_M14EBRSP_SD"
,"RH_MK21A5SD"
,"RH_MK12sd"
,"RH_MK12mod1sd"
,"RH_mk14ebrsp_sd"
,"SCAR_H_LNG_Sniper_SD"
,"VSS_vintorez"
,"RH_ak105sp"
,"RH_ak105glsp"
,"RH_AK107sp"
,"RH_AK107glsp"
,"RH_ak74sp"
,"RH_ak74msp"
,"RH_ak74mglsp"
,"RH_aks74sp"
,"RH_aks74msp"
,"RH_aks74mglsp"
,"RH_aks74psp"
,"RH_aks74pglsp"
,"RH_oc14glsp"
,"SVD_des_EP1"
,"RH_SVDb"
,"SVD_CAMO"
,"SVD"
,"RH_SVDg"
,"SVD_NSPU_EP1"
,"RH_SVDs"
,"RH_SVU"
,"RH_ak104sp"
,"FN_FAL_ANPVS4"
,"RH_gr1sp"
,"RH_oc14sp"
,"RH_hk417sp"
,"RH_SVD"
,"RH_sc2sp"
,"SCAR_H_LNG_Sniper"
,"mcno_SCAR_H_LNG_Sniper_WHITE"
,"LEXX_SCAR_H_LNG_Sniper_BLACK"
,"MCNO_M110_NVG_EP1_WHITE"
,"LEXX_M110_NVG_EP1_BLACK"
,"M110_NVG_EP1"
,"RH_M14EBRSP"
,"RH_m1ssp"
,"RH_MK12"
,"RH_MK12mod1"
,"M4SPR"
,"RH_mk14ebrsp"
,"RH_aks74uptsp"
,"RH_ak104glsp"
,"RH_ak103glsp"
,"AKS_74_NSPU"
,"RH_m1stsp"
,"RH_MK21A5"
,"M24"
,"M24_des_EP1"
,"RH_m21"
,"M40A3"
,"RH_M40A3"
,"RH_M40A5"
,"DMR_SKN"
,"RH_ak103sp"
,"RH_akmsp"
,"huntingrifle"
,"RH_M40A1"
,"m8_sharpshooter"
,"RH_M14EBRGC_SD"
,"RH_M14EBRGC"
,"BAF_L110A1_Aim_FDZ"
,"BAF_L7A2_GPMG_FDZ"
,"M240_FDZ"
,"m240_scoped_EP1_DZE"
,"M249_FDZ"
,"M249_EP1_DZ"
,"M249_m145_EP1_DZE"
,"M60A4_EP1_DZE"
,"Mcno_M249_m145_EP1_white_FDZ"
,"MG36_FDZ"
,"MG36_camo_FDZ"
,"Mk_48_DES_EP1_FDZ"
,"Mk_48_DZ"
,"Pecheneg_DZ"
,"PK_DZ"
,"RH_M249_FDZ"
,"RH_M249acog_FDZ"
,"RH_M249elcan_FDZ"
,"RH_M249p_FDZ"
,"RH_M249pacog_FDZ"
,"RH_M249pelcan_FDZ"
,"RH_M60E4_FDZ"
,"RH_M60E4_ACOG_FDZ"
,"RH_M60E4_ELCAN_FDZ"
,"RH_M60E4_EOTECH_FDZ"
,"RH_MK43_FDZ"
,"RH_MK43_ACOG_FDZ"
,"RH_MK43_ELCAN_FDZ"
,"RH_MK43_EOTECH_FDZ"
,"RH_Mk48mod1_FDZ"
,"RH_Mk48mod1acog_FDZ"
,"RH_Mk48mod1elcan_FDZ"
,"RH_rpk47_FDZ"
,"RH_rpk74_FDZ"
,"RH_rpk74m_FDZ"
,"RPK_74_FDZ"
,"RPK_74_Large_FDZ"
,"ukf_gpmg_FDZ"
,"ukf_gpmg_fgrip_FDZ"
,"ukf_L86A2LSW_FDZ"
,"ukf_L86A2LSW_fgrip_FDZ"
,"ukf_L86A2LSW_susat_FDZ"
,"ukf_L86A2LSW_susat_fgrip_FDZ"
,"ukf_lmg_FDZ"
,"ukf_lmg_ACOG_FDZ"
,"ukf_lmg_ACOG_fgrip_FDZ"
,"ukf_lmg_fgrip_FDZ"
,"ukf_lmg_SUSAT_FDZ"
,"ukf_lmg_SUSAT_fgrip_FDZ"]; //Weapongrade 0 rifles
DZAI_Rifles1 = ["Winchester1866"
,"AA12_PMC"
,"MR43"
,"M1014"
,"Remington870"
,"Remington870_lamp"
,"Saiga12K"
,"RH_acr"
,"RH_acracog"
,"RH_acraim"
,"RH_acrb"
,"RH_acrbacog"
,"RH_acrbaim"
,"RH_acrbeotech"
,"RH_acrbgl"
,"RH_acrbglacog"
,"RH_acrbglaim"
,"RH_acrbgleotech"
,"RH_acreotech"
,"RH_acrgl"
,"RH_acrglacog"
,"RH_acrglaim"
,"RH_acrgleotech"
,"RH_hk416"
,"RH_hk416acog"
,"RH_hk416aim"
,"RH_hk416eotech"
,"RH_hk416gl"
,"RH_hk416glacog"
,"RH_hk416glaim"
,"RH_hk416gleotech"
,"RH_hk416s"
,"RH_hk416sacog"
,"RH_hk416saim"
,"RH_hk416sd"
,"RH_hk416sdaim"
,"RH_hk416sdeotech"
,"RH_hk416sdgl"
,"RH_hk416sdglaim"
,"RH_hk416sdgleotech"
,"RH_hk416seotech"
,"RH_hk416sgl"
,"RH_hk416sglacog"
,"RH_hk416sglaim"
,"RH_hk416sgleotech"
,"RH_hk417"
,"RH_hk417acog"
,"RH_hk417aim"
,"RH_hk417eotech"
,"RH_hk417s"
,"RH_hk417sacog"
,"RH_hk417saim"
,"RH_hk417sd"
,"RH_hk417sdacog"
,"RH_hk417sdaim"
,"RH_hk417sdeotech"
,"RH_hk417seotech"
,"RH_hk417sgl"
,"RH_hk417sglacog"
,"RH_hk417sglaim"
,"RH_hk417sgleotech"
,"G36_C_SD_camo"
,"G36_C_SD_eotech"
,"G36a"
,"G36A_camo"
,"G36C"
,"G36C_camo"
,"G36K"
,"G36K_camo"
,"AK_107_GL_kobra"
,"AK_107_GL_pso"
,"AK_107_kobra"
,"AK_107_pso"
,"AK_47_M"
,"AK_47_S"
,"AK_74"
,"AK_74_GL"
,"AK_74_GL_kobra"
,"AKS_74"
,"AKS_74_kobra"
,"AKS_74_pso"
,"AKS_74_U"
,"AKS_74_UN_kobra"
,"AKS_GOLD"
,"RH_AK102"
,"RH_AK102GL"
,"RH_ak103"
,"RH_ak103gl"
,"RH_ak103k"
,"RH_ak103kgl"
,"RH_ak104"
,"RH_ak104_1p29"
,"RH_ak104gl"
,"RH_ak104k"
,"RH_ak104kgl"
,"RH_ak105"
,"RH_ak105gl"
,"RH_ak105k"
,"RH_ak105kgl"
,"RH_AK107"
,"RH_AK107gl"
,"RH_AK107k"
,"RH_AK107kgl"
,"RH_ak47"
,"RH_ak47gl"
,"RH_ak74"
,"RH_ak74gl"
,"RH_ak74k"
,"RH_ak74kgl"
,"RH_ak74m"
,"RH_ak74mgl"
,"RH_ak74mk"
,"RH_ak74mkgl"
,"RH_akm"
,"RH_akmgl"
,"RH_akms"
,"RH_akmssd"
,"RH_aks47"
,"RH_aks47b"
,"RH_aks47g"
,"RH_aks47s"
,"RH_aks74"
,"RH_aks74gl"
,"RH_aks74k"
,"RH_aks74kgl"
,"RH_aks74m"
,"RH_aks74mgl"
,"RH_aks74mgl1p29"
,"RH_aks74mk"
,"RH_aks74mkgl"
,"RH_aks74p"
,"RH_aks74pgl"
,"RH_aks74pk"
,"RH_aks74pkgl"
,"RH_aks74u"
,"RH_aks74uk"
,"RH_aks74upt"
,"RH_aks74uptk"
,"RH_aks74usd"
,"RH_aks74usdk"
,"RH_rk95"
,"RH_Rk95ag"
,"RH_Rk95aim"
,"RH_Rk95sd"
,"RH_Rk95sdag"
,"RH_Rk95sdaim"
,"Sa58P_EP1"
,"Sa58V_CCO_EP1"
,"Sa58V_EP1"
,"Sa58V_RCO_EP1"
,"BAF_L85A2_RIS_ACOG"
,"BAF_L85A2_RIS_CWS"
,"BAF_L85A2_RIS_Holo"
,"BAF_L85A2_RIS_SUSAT"
,"BAF_L85A2_UGL_ACOG"
,"BAF_L85A2_UGL_Holo"
,"BAF_L85A2_UGL_SUSAT"
,"ukf_L85A2"
,"ukf_L85A2_acog"
,"ukf_L85A2_acog_CQB"
,"ukf_L85A2_RIS"
,"ukf_L85A2_sd"
,"ukf_L85A2_sd_CQB"
,"ukf_L85A2_susat"
,"ukf_L85A2AG36"
,"ukf_L85A2AG36_acog"
,"ukf_L85A2AG36_acog_CQB"
,"ukf_L85A2AG36_acog_fgrip"
,"ukf_L85A2AG36_acog_fgrip_CQB"
,"ukf_L85A2AG36_fgrip"
,"ukf_L85A2AG36_sd"
,"ukf_L85A2AG36_sd_CQB"
,"ukf_L85A2AG36_sd_fgrip"
,"ukf_L85A2AG36_sd_fgrip_CQB"
,"ukf_L85A2AG36_susat"
,"ukf_L85A2AG36_susat_fgrip"
,"ukf_L85A2K_susat"
,"ukf_L86A2LSW"
,"ukf_L86A2LSW_fgrip"
,"ukf_L86A2LSW_susat"
,"ukf_L86A2LSW_susat_fgrip"
,"M4A1"
,"M4A1_Aim"
,"M4A1_Aim_camo"
,"M4A1_AIM_SD_camo"
,"M4A1_HWS_GL"
,"M4A1_HWS_GL_camo"
,"M4A1_HWS_GL_SD_Camo"
,"M4A1_RCO_GL"
,"M4A3_CCO_EP1"
,"M4A3_RCO_GL_EP1"
,"RH_M4"
,"RH_M4a1"
,"RH_M4a1acog"
,"RH_M4a1aim"
,"RH_M4a1eotech"
,"RH_M4a1gl"
,"RH_M4a1glacog"
,"RH_M4a1glaim"
,"RH_M4a1gleotech"
,"RH_M4a1r"
,"RH_M4acog"
,"RH_M4aim"
,"RH_M4aim_wdl"
,"RH_M4C"
,"RH_M4CACOG"
,"RH_M4CAIM"
,"RH_M4CEOTECH"
,"RH_M4CGL"
,"RH_M4CGLACOG"
,"RH_M4CGLAIM"
,"RH_M4CGLEOTECH"
,"RH_M4CMK"
,"RH_M4CMKACOG"
,"RH_M4CMKAIM"
,"RH_M4CMKEOTECH"
,"RH_M4CS"
,"RH_M4CSACOG"
,"RH_M4CSAIM"
,"RH_M4CSEOTECH"
,"RH_M4CT"
,"RH_M4CT_F"
,"RH_M4CTSD"
,"RH_M4CTSD_F"
,"RH_M4CTSDACOG"
,"RH_M4CTSDACOG_F"
,"RH_M4CTSDAIM"
,"RH_M4CTSDAIM_F"
,"RH_M4CTSDEOTECH"
,"RH_M4CTSDEOTECH_F"
,"RH_M4CTSDGL"
,"RH_M4CTSDGL_F"
,"RH_M4CTSDGLACOG"
,"RH_M4CTSDGLACOG_F"
,"RH_M4CTSDGLAIM"
,"RH_M4CTSDGLAIM_F"
,"RH_M4CTSDGLEOTECH"
,"RH_M4CTSDGLEOTECH_F"
,"RH_M4eotech"
,"RH_M4gl"
,"RH_M4glacog"
,"RH_M4glaim"
,"RH_M4gleotech"
,"RH_M4gleotech_wdl"
,"RH_M4m"
,"RH_M4macog"
,"RH_M4maim"
,"RH_M4meotech"
,"RH_M4r"
,"RH_M4sbr"
,"RH_M4sbracog"
,"RH_M4sbraim"
,"RH_M4sbreotech"
,"RH_M4sd"
,"RH_M4sdacog"
,"RH_M4sdaim"
,"RH_M4sdaim_wdl"
,"RH_M4sdeotech"
,"RH_M4sdgl"
,"RH_M4sdglacog"
,"RH_M4sdglaim"
,"RH_M4sdgleotech"
,"RH_M4sdgleotech_wdl"
,"m8_carbine"
,"m8_carbine_pmc"
,"m8_carbineGL"
,"m8_compact"
,"m8_compact_pmc"
,"m8_holo_sd"
,"m8_SAW"
,"RH_XM8"
,"RH_XM8C"
,"RH_XM8D"
,"RH_XM8DC"
,"RH_XM8DGL"
,"RH_XM8DSAW"
,"RH_XM8DSH"
,"RH_XM8GL"
,"RH_XM8SAW"
,"RH_XM8SH"
,"M16A2"
,"M16A2GL"
,"m16a4"
,"m16a4_acg"
,"M16A4_ACG_GL"
,"M16A4_GL"
,"RH_M16a1"
,"RH_M16a1gl"
,"RH_M16a1s"
,"RH_M16a1sgl"
,"RH_m16a2"
,"RH_m16a2aim"
,"RH_M16a2gl"
,"RH_M16a2glaim"
,"RH_M16a2s"
,"RH_M16a2sgl"
,"RH_M16a3"
,"RH_M16a3aim"
,"RH_M16a3c"
,"RH_M16a3cs"
,"RH_M16a3gl"
,"RH_M16a3s"
,"RH_M16a3sgl"
,"RH_M16a4"
,"RH_M16A4acog"
,"RH_M16A4aim"
,"RH_M16A4eotech"
,"RH_M16a4gl"
,"RH_M16A4glacog"
,"RH_M16A4glaim"
,"RH_M16A4gleotech"
,"RH_mas"
,"RH_masacog"
,"RH_masaim"
,"RH_masb"
,"RH_masbacog"
,"RH_masbaim"
,"RH_masbeotech"
,"RH_masbsd"
,"RH_masbsdacog"
,"RH_masbsdaim"
,"RH_masbsdeotech"
,"RH_maseotech"
,"RH_massd"
,"RH_massdacog"
,"RH_massdaim"
,"RH_massdeotech"
,"FN_FAL"
,"LeeEnfield"
,"RH_star21"
,"RH_an94"
,"RH_an94gl"
,"RH_ar10"
,"RH_ar10s"
,"RH_asval"
,"RH_asvalk"
,"RH_ctar21"
,"RH_ctar21glacog"
,"RH_ctar21m"
,"RH_ctar21mgl"
,"RH_Mk18"
,"RH_Mk18acog"
,"RH_Mk18aim"
,"RH_Mk18d"
,"RH_Mk18dacog"
,"RH_Mk18daim"
,"RH_mk18dc"
,"RH_mk18dcacog"
,"RH_mk18dcaim"
,"RH_mk18dceot"
,"RH_mk18dcgl"
,"RH_mk18dcglacog"
,"RH_mk18dcglaim"
,"RH_mk18dcgleot"
,"RH_mk18dcsd"
,"RH_mk18dcsdacog"
,"RH_mk18dcsdaim"
,"RH_mk18dcsdeot"
,"RH_Mk18deot"
,"RH_Mk18dgl"
,"RH_Mk18dglacog"
,"RH_Mk18dglaim"
,"RH_Mk18dgleot"
,"RH_Mk18dsd"
,"RH_Mk18dsdacog"
,"RH_Mk18dsdaim"
,"RH_Mk18dsdeot"
,"RH_Mk18eot"
,"RH_Mk18gl"
,"RH_Mk18glacog"
,"RH_Mk18glaim"
,"RH_Mk18gleot"
,"RH_Mk18sd"
,"RH_Mk18sdacog"
,"RH_Mk18sdaim"
,"RH_Mk18sdeot"
,"RH_Mk18t"
,"LEXX_SCAR_H_CQC_CCO_BLACK"
,"LEXX_SCAR_H_CQC_CCO_SD_BLACK"
,"LEXX_SCAR_H_STD_EGLM_Spect_BLACK"
,"LEXX_SCAR_L_CQC_BLACK"
,"LEXX_SCAR_L_CQC_CCO_SD_BLACK"
,"LEXX_SCAR_L_CQC_EGLM_Holo_BLACK"
,"LEXX_SCAR_L_CQC_Holo_BLACK"
,"LEXX_SCAR_L_STD_EGLM_RCO_BLACK"
,"LEXX_SCAR_L_STD_HOLO_BLACK"
,"LEXX_SCAR_L_STD_Mk4CQT_BLACK"
,"mcno_SCAR_H_CQC_CCO_SD_WHITE"
,"mcno_SCAR_H_CQC_CCO_WHITE"
,"mcno_SCAR_H_STD_EGLM_Spect_WHITE"
,"mcno_SCAR_L_CQC_CCO_SD_WHITE"
,"mcno_SCAR_L_CQC_EGLM_Holo_WHITE"
,"mcno_SCAR_L_CQC_Holo_WHITE"
,"mcno_SCAR_L_CQC_WHITE"
,"mcno_SCAR_L_STD_EGLM_RCO_WHITE"
,"mcno_SCAR_L_STD_HOLO_WHITE"
,"mcno_SCAR_L_STD_Mk4CQT_WHITE"
,"RH_SCARAK"
,"RH_SCARAKACOG"
,"RH_SCARAKAIM"
,"RH_SCARAKBAIM"
,"RH_SCARAKEOTECH"
,"RH_SCARH"
,"RH_SCARH_ACOG"
,"RH_SCARH_AIM"
,"RH_SCARH_EOTECH"
,"RH_SCARH_GL"
,"RH_SCARH_GL_ACOG"
,"RH_SCARH_GL_AIM"
,"RH_SCARH_GL_EOTECH"
,"RH_SCARH_GL_SPECTERDR"
,"RH_SCARH_MK4"
,"RH_SCARH_SD_ACOG"
,"RH_SCARH_SD_AIM"
,"RH_SCARH_SD_EOTECH"
,"RH_SCARH_SD_GL_AIM"
,"RH_SCARH_SD_GL_EOTECH"
,"RH_SCARH_SPECTERDR"
,"RH_SCARHB_EOTECH"
,"RH_SCARHB_GL_ACOG"
,"RH_SCARHB_SD_AIM"
,"RH_SCARHB_SD_GL_EOTECH"
,"RH_SCARL"
,"RH_SCARL_ACOG"
,"RH_SCARL_AIM"
,"RH_SCARL_DOC"
,"RH_SCARL_EOTECH"
,"RH_SCARL_GL"
,"RH_SCARL_GL_ACOG"
,"RH_SCARL_GL_AIM"
,"RH_SCARL_GL_EOTECH"
,"RH_SCARL_MK4"
,"RH_SCARL_SD_ACOG"
,"RH_SCARL_SD_AIM"
,"RH_SCARL_SD_DOC"
,"RH_SCARL_SD_EOTECH"
,"RH_SCARL_SD_GL_ACOG"
,"RH_SCARL_SD_GL_AIM"
,"RH_SCARL_SD_GL_EOTECH"
,"RH_SCARLB_AIM"
,"RH_SCARLB_GL_ACOG"
,"RH_SCARLB_SD_EOTECH"
,"RH_SCARLB_SD_GL_AIM"
,"SCAR_H_CQC_CCO"
,"SCAR_H_CQC_CCO_SD"
,"SCAR_H_STD_EGLM_Spect"
,"SCAR_L_CQC"
,"SCAR_L_CQC_CCO_SD"
,"SCAR_L_CQC_EGLM_Holo"
,"SCAR_L_CQC_Holo"
,"SCAR_L_STD_EGLM_RCO"
,"SCAR_L_STD_HOLO"
,"SCAR_L_STD_Mk4CQT"
,"RH_p90sdaim"
,"RH_p90sdeot"
,"RH_p90isd"
,"RH_mp5sd6aim"
,"RH_mp5sd6g"
,"RH_mp5sd6eot"
,"RH_mp5sd6RFX"
,"RH_mp7sdaim"
,"RH_mp7sdeot"
,"RH_umpsdaim"
,"RH_umpsdeot"
,"RH_umpsdRFX"
,"MP5SD"
,"RH_krisssdaim"
,"RH_krisssdeot"
,"RH_krisssdRFX"
,"RH_tmpsdaim"
,"RH_P90sd"
,"RH_mp5sd6"
,"RH_mp7sd"
,"RH_umpsd"
,"RH_krisssd"
,"RH_tmpsd"
,"RH_tmpsdeot"
,"RH_uzisd"
,"bizon_silenced"
,"RH_bizonsd"
,"RH_bizonsdk"
,"RH_P90aim"
,"RH_P90eot"
,"RH_P90i"
,"RH_HK53aim"
,"RH_HK53eot"
,"RH_HK53RFX"
,"RH_mp5a4aim"
,"RH_mp5a4eot"
,"RH_mp5a4RFX"
,"RH_mp5a5"
,"RH_mp5a5aim"
,"RH_mp5a5eodaim"
,"RH_mp5a5eodeot"
,"RH_mp5a5eodRFX"
,"RH_mp5a5eot"
,"RH_mp5a5eod"
,"RH_mp5a5RFX"
,"RH_mp5a5ris"
,"RH_mp5a5risaim"
,"RH_mp5a5riseot"
,"RH_mp5a5risRFX"
,"RH_mp5k"
,"RH_mp5kpdw"
,"RH_mp5kpdwaim"
,"RH_mp5kpdweot"
,"RH_mp5kpdwRFX"
,"RH_mp7aim"
,"RH_mp7eot"
,"RH_umpaim"
,"RH_umpRFX"
,"RH_bizon"
,"RH_bizonk"
,"bizon"
,"RH_P90"
,"RH_HK53"
,"RH_mp5a4"
,"RH_mp7"
,"RH_UMP"
,"RH_umpeot"
,"RH_mac10"
,"RH_PDR"
,"RH_pdraim"
,"RH_pdreot"
,"RH_PDW_AIM"
,"RH_PDW_EOTECH"
,"RH_krissaim"
,"RH_krisseot"
,"RH_krissRFX"
,"RH_tmpeot"
,"RH_uzig"
,"RH_uzim"
,"RH_pp2000"
,"RH_pp2000eot"
,"RH_PDW"
,"RH_PDW_ACOG"
,"RH_fmg9"
,"MP5A5"
,"RH_pp2000aim"
,"RH_tmp"
,"RH_kriss"
,"RH_tmpaim"
,"RH_uzi"
,"MIDF_Aug_A3"
,"MIDF_Aug_A3_acog"
,"MIDF_Aug_A3_acog_black"
,"MIDF_Aug_A3_acog_blue"
,"MIDF_Aug_A3_ACOG_GL"
,"MIDF_Aug_A3_ACOG_GL_BLACK"
,"MIDF_Aug_A3_ACOG_GL_BLUE"
,"MIDF_Aug_A3_Black"
,"MIDF_Aug_A3_Blue"
,"MIDF_Aug_A3_eotech"
,"MIDF_Aug_A3_eotech_black"
,"MIDF_Aug_A3_eotech_blue"
,"MIDF_Aug_A3_EOTECH_GL"
,"MIDF_Aug_A3_EOTECH_GL_BLACK"
,"MIDF_Aug_A3_EOTECH_GL_BLUE"
,"MIDF_Aug_A3_GL"
,"MIDF_Aug_A3_GL_black"
,"MIDF_Aug_A3_GL_blue"
,"M14_EP1"
,"RH_gr1"
,"RH_gr1sd"
,"RH_m14"
,"RH_m14acog"
,"RH_m14aim"
,"RH_M14EBR"
,"RH_M14EBR_SD"
,"RH_m14eot"
,"RH_m1s"
,"RH_m1sacog"
,"RH_m1saim"
,"RH_m1seot"
,"RH_m1sshd"
,"RH_m1st"
,"RH_m1stacog"
,"RH_m1staim"
,"RH_m1steot"
,"RH_m1stshd"
,"RH_m39emr"
,"RH_MK14"
,"RH_MK14ACOG"
,"RH_MK14AIM"
,"RH_mk14ebr"
,"RH_mk14ebr_sd"
,"RH_mk14ebrgc"
,"RH_mk14ebrgc_sd"
,"RH_MK14EOTECH"
,"RH_MK14SD"
,"RH_MK14SDACOG"
,"RH_MK14SDAIM"
,"RH_MK14SDEOTECH"
,"RH_mk14t"
,"RH_mk14tacog"
,"RH_mk14taim"
,"RH_mk14teot"
,"RH_mk14tsd"
,"RH_mk14tsdacog"
,"RH_mk14tsdaim"
,"RH_mk14tsdeot"
,"RH_oc14"
,"RH_oc14gl"
,"RH_oc14sd"
,"RH_sc2"
,"RH_sc2acog"
,"RH_sc2aim"
,"RH_sc2eot"
,"RH_sc2shd"
,"UKF_L115A3_fgrip"
,"UKF_L115A3_des"
,"UKF_L115A3_wdl_fgrip"
,"BAF_LRR_scoped"
,"UKF_L115A3_sd_fgrip"
,"UKF_L115A3_sd"
,"UKF_L115A3_sd_des"
,"UKF_L115A3_sd_des_fgrip"
,"UKF_L115A3_sd_wdl"
,"BAF_AS50_scoped_DZ"
,"BAF_LRR_scoped_W"
,"UKF_L115A3"
,"UKF_L115A3_des_fgrip"
,"UKF_L115A3_wdl"
,"UKF_L115A3_sd_wdl_fgrip"
,"m107_SKN"
,"USSR_cheytacM200_FDZ"
,"USSR_cheytacM200_sd_FDZ"
,"KSVK_DZE"
,"LEXX_SCAR_H_LNG_Sniper_SD_BLACK"
,"mcno_SCAR_H_LNG_Sniper_SD_WHITE"
,"RH_asvalsp"
,"RH_gr1sdsp"
,"RH_oc14sdsp"
,"RH_hk417sdsp"
,"RH_M14EBRSP_SD"
,"RH_MK21A5SD"
,"RH_MK12sd"
,"RH_MK12mod1sd"
,"RH_mk14ebrsp_sd"
,"SCAR_H_LNG_Sniper_SD"
,"VSS_vintorez"
,"RH_ak105sp"
,"RH_ak105glsp"
,"RH_AK107sp"
,"RH_AK107glsp"
,"RH_ak74sp"
,"RH_ak74msp"
,"RH_ak74mglsp"
,"RH_aks74sp"
,"RH_aks74msp"
,"RH_aks74mglsp"
,"RH_aks74psp"
,"RH_aks74pglsp"
,"RH_oc14glsp"
,"SVD_des_EP1"
,"RH_SVDb"
,"SVD_CAMO"
,"SVD"
,"RH_SVDg"
,"SVD_NSPU_EP1"
,"RH_SVDs"
,"RH_SVU"
,"RH_ak104sp"
,"FN_FAL_ANPVS4"
,"RH_gr1sp"
,"RH_oc14sp"
,"RH_hk417sp"
,"RH_SVD"
,"RH_sc2sp"
,"SCAR_H_LNG_Sniper"
,"mcno_SCAR_H_LNG_Sniper_WHITE"
,"LEXX_SCAR_H_LNG_Sniper_BLACK"
,"MCNO_M110_NVG_EP1_WHITE"
,"LEXX_M110_NVG_EP1_BLACK"
,"M110_NVG_EP1"
,"RH_M14EBRSP"
,"RH_m1ssp"
,"RH_MK12"
,"RH_MK12mod1"
,"M4SPR"
,"RH_mk14ebrsp"
,"RH_aks74uptsp"
,"RH_ak104glsp"
,"RH_ak103glsp"
,"AKS_74_NSPU"
,"RH_m1stsp"
,"RH_MK21A5"
,"M24"
,"M24_des_EP1"
,"RH_m21"
,"M40A3"
,"RH_M40A3"
,"RH_M40A5"
,"DMR_SKN"
,"RH_ak103sp"
,"RH_akmsp"
,"huntingrifle"
,"RH_M40A1"
,"m8_sharpshooter"
,"RH_M14EBRGC_SD"
,"RH_M14EBRGC"
,"BAF_L110A1_Aim_FDZ"
,"BAF_L7A2_GPMG_FDZ"
,"M240_FDZ"
,"m240_scoped_EP1_DZE"
,"M249_FDZ"
,"M249_EP1_DZ"
,"M249_m145_EP1_DZE"
,"M60A4_EP1_DZE"
,"Mcno_M249_m145_EP1_white_FDZ"
,"MG36_FDZ"
,"MG36_camo_FDZ"
,"Mk_48_DES_EP1_FDZ"
,"Mk_48_DZ"
,"Pecheneg_DZ"
,"PK_DZ"
,"RH_M249_FDZ"
,"RH_M249acog_FDZ"
,"RH_M249elcan_FDZ"
,"RH_M249p_FDZ"
,"RH_M249pacog_FDZ"
,"RH_M249pelcan_FDZ"
,"RH_M60E4_FDZ"
,"RH_M60E4_ACOG_FDZ"
,"RH_M60E4_ELCAN_FDZ"
,"RH_M60E4_EOTECH_FDZ"
,"RH_MK43_FDZ"
,"RH_MK43_ACOG_FDZ"
,"RH_MK43_ELCAN_FDZ"
,"RH_MK43_EOTECH_FDZ"
,"RH_Mk48mod1_FDZ"
,"RH_Mk48mod1acog_FDZ"
,"RH_Mk48mod1elcan_FDZ"
,"RH_rpk47_FDZ"
,"RH_rpk74_FDZ"
,"RH_rpk74m_FDZ"
,"RPK_74_FDZ"
,"RPK_74_Large_FDZ"
,"ukf_gpmg_FDZ"
,"ukf_gpmg_fgrip_FDZ"
,"ukf_L86A2LSW_FDZ"
,"ukf_L86A2LSW_fgrip_FDZ"
,"ukf_L86A2LSW_susat_FDZ"
,"ukf_L86A2LSW_susat_fgrip_FDZ"
,"ukf_lmg_FDZ"
,"ukf_lmg_ACOG_FDZ"
,"ukf_lmg_ACOG_fgrip_FDZ"
,"ukf_lmg_fgrip_FDZ"
,"ukf_lmg_SUSAT_FDZ"
,"ukf_lmg_SUSAT_fgrip_FDZ"]; //Weapongrade 1 rifles
DZAI_Rifles2 = ["Winchester1866"
,"AA12_PMC"
,"MR43"
,"M1014"
,"Remington870"
,"Remington870_lamp"
,"Saiga12K"
,"RH_acr"
,"RH_acracog"
,"RH_acraim"
,"RH_acrb"
,"RH_acrbacog"
,"RH_acrbaim"
,"RH_acrbeotech"
,"RH_acrbgl"
,"RH_acrbglacog"
,"RH_acrbglaim"
,"RH_acrbgleotech"
,"RH_acreotech"
,"RH_acrgl"
,"RH_acrglacog"
,"RH_acrglaim"
,"RH_acrgleotech"
,"RH_hk416"
,"RH_hk416acog"
,"RH_hk416aim"
,"RH_hk416eotech"
,"RH_hk416gl"
,"RH_hk416glacog"
,"RH_hk416glaim"
,"RH_hk416gleotech"
,"RH_hk416s"
,"RH_hk416sacog"
,"RH_hk416saim"
,"RH_hk416sd"
,"RH_hk416sdaim"
,"RH_hk416sdeotech"
,"RH_hk416sdgl"
,"RH_hk416sdglaim"
,"RH_hk416sdgleotech"
,"RH_hk416seotech"
,"RH_hk416sgl"
,"RH_hk416sglacog"
,"RH_hk416sglaim"
,"RH_hk416sgleotech"
,"RH_hk417"
,"RH_hk417acog"
,"RH_hk417aim"
,"RH_hk417eotech"
,"RH_hk417s"
,"RH_hk417sacog"
,"RH_hk417saim"
,"RH_hk417sd"
,"RH_hk417sdacog"
,"RH_hk417sdaim"
,"RH_hk417sdeotech"
,"RH_hk417seotech"
,"RH_hk417sgl"
,"RH_hk417sglacog"
,"RH_hk417sglaim"
,"RH_hk417sgleotech"
,"G36_C_SD_camo"
,"G36_C_SD_eotech"
,"G36a"
,"G36A_camo"
,"G36C"
,"G36C_camo"
,"G36K"
,"G36K_camo"
,"AK_107_GL_kobra"
,"AK_107_GL_pso"
,"AK_107_kobra"
,"AK_107_pso"
,"AK_47_M"
,"AK_47_S"
,"AK_74"
,"AK_74_GL"
,"AK_74_GL_kobra"
,"AKS_74"
,"AKS_74_kobra"
,"AKS_74_pso"
,"AKS_74_U"
,"AKS_74_UN_kobra"
,"AKS_GOLD"
,"RH_AK102"
,"RH_AK102GL"
,"RH_ak103"
,"RH_ak103gl"
,"RH_ak103k"
,"RH_ak103kgl"
,"RH_ak104"
,"RH_ak104_1p29"
,"RH_ak104gl"
,"RH_ak104k"
,"RH_ak104kgl"
,"RH_ak105"
,"RH_ak105gl"
,"RH_ak105k"
,"RH_ak105kgl"
,"RH_AK107"
,"RH_AK107gl"
,"RH_AK107k"
,"RH_AK107kgl"
,"RH_ak47"
,"RH_ak47gl"
,"RH_ak74"
,"RH_ak74gl"
,"RH_ak74k"
,"RH_ak74kgl"
,"RH_ak74m"
,"RH_ak74mgl"
,"RH_ak74mk"
,"RH_ak74mkgl"
,"RH_akm"
,"RH_akmgl"
,"RH_akms"
,"RH_akmssd"
,"RH_aks47"
,"RH_aks47b"
,"RH_aks47g"
,"RH_aks47s"
,"RH_aks74"
,"RH_aks74gl"
,"RH_aks74k"
,"RH_aks74kgl"
,"RH_aks74m"
,"RH_aks74mgl"
,"RH_aks74mgl1p29"
,"RH_aks74mk"
,"RH_aks74mkgl"
,"RH_aks74p"
,"RH_aks74pgl"
,"RH_aks74pk"
,"RH_aks74pkgl"
,"RH_aks74u"
,"RH_aks74uk"
,"RH_aks74upt"
,"RH_aks74uptk"
,"RH_aks74usd"
,"RH_aks74usdk"
,"RH_rk95"
,"RH_Rk95ag"
,"RH_Rk95aim"
,"RH_Rk95sd"
,"RH_Rk95sdag"
,"RH_Rk95sdaim"
,"Sa58P_EP1"
,"Sa58V_CCO_EP1"
,"Sa58V_EP1"
,"Sa58V_RCO_EP1"
,"BAF_L85A2_RIS_ACOG"
,"BAF_L85A2_RIS_CWS"
,"BAF_L85A2_RIS_Holo"
,"BAF_L85A2_RIS_SUSAT"
,"BAF_L85A2_UGL_ACOG"
,"BAF_L85A2_UGL_Holo"
,"BAF_L85A2_UGL_SUSAT"
,"ukf_L85A2"
,"ukf_L85A2_acog"
,"ukf_L85A2_acog_CQB"
,"ukf_L85A2_RIS"
,"ukf_L85A2_sd"
,"ukf_L85A2_sd_CQB"
,"ukf_L85A2_susat"
,"ukf_L85A2AG36"
,"ukf_L85A2AG36_acog"
,"ukf_L85A2AG36_acog_CQB"
,"ukf_L85A2AG36_acog_fgrip"
,"ukf_L85A2AG36_acog_fgrip_CQB"
,"ukf_L85A2AG36_fgrip"
,"ukf_L85A2AG36_sd"
,"ukf_L85A2AG36_sd_CQB"
,"ukf_L85A2AG36_sd_fgrip"
,"ukf_L85A2AG36_sd_fgrip_CQB"
,"ukf_L85A2AG36_susat"
,"ukf_L85A2AG36_susat_fgrip"
,"ukf_L85A2K_susat"
,"ukf_L86A2LSW"
,"ukf_L86A2LSW_fgrip"
,"ukf_L86A2LSW_susat"
,"ukf_L86A2LSW_susat_fgrip"
,"M4A1"
,"M4A1_Aim"
,"M4A1_Aim_camo"
,"M4A1_AIM_SD_camo"
,"M4A1_HWS_GL"
,"M4A1_HWS_GL_camo"
,"M4A1_HWS_GL_SD_Camo"
,"M4A1_RCO_GL"
,"M4A3_CCO_EP1"
,"M4A3_RCO_GL_EP1"
,"RH_M4"
,"RH_M4a1"
,"RH_M4a1acog"
,"RH_M4a1aim"
,"RH_M4a1eotech"
,"RH_M4a1gl"
,"RH_M4a1glacog"
,"RH_M4a1glaim"
,"RH_M4a1gleotech"
,"RH_M4a1r"
,"RH_M4acog"
,"RH_M4aim"
,"RH_M4aim_wdl"
,"RH_M4C"
,"RH_M4CACOG"
,"RH_M4CAIM"
,"RH_M4CEOTECH"
,"RH_M4CGL"
,"RH_M4CGLACOG"
,"RH_M4CGLAIM"
,"RH_M4CGLEOTECH"
,"RH_M4CMK"
,"RH_M4CMKACOG"
,"RH_M4CMKAIM"
,"RH_M4CMKEOTECH"
,"RH_M4CS"
,"RH_M4CSACOG"
,"RH_M4CSAIM"
,"RH_M4CSEOTECH"
,"RH_M4CT"
,"RH_M4CT_F"
,"RH_M4CTSD"
,"RH_M4CTSD_F"
,"RH_M4CTSDACOG"
,"RH_M4CTSDACOG_F"
,"RH_M4CTSDAIM"
,"RH_M4CTSDAIM_F"
,"RH_M4CTSDEOTECH"
,"RH_M4CTSDEOTECH_F"
,"RH_M4CTSDGL"
,"RH_M4CTSDGL_F"
,"RH_M4CTSDGLACOG"
,"RH_M4CTSDGLACOG_F"
,"RH_M4CTSDGLAIM"
,"RH_M4CTSDGLAIM_F"
,"RH_M4CTSDGLEOTECH"
,"RH_M4CTSDGLEOTECH_F"
,"RH_M4eotech"
,"RH_M4gl"
,"RH_M4glacog"
,"RH_M4glaim"
,"RH_M4gleotech"
,"RH_M4gleotech_wdl"
,"RH_M4m"
,"RH_M4macog"
,"RH_M4maim"
,"RH_M4meotech"
,"RH_M4r"
,"RH_M4sbr"
,"RH_M4sbracog"
,"RH_M4sbraim"
,"RH_M4sbreotech"
,"RH_M4sd"
,"RH_M4sdacog"
,"RH_M4sdaim"
,"RH_M4sdaim_wdl"
,"RH_M4sdeotech"
,"RH_M4sdgl"
,"RH_M4sdglacog"
,"RH_M4sdglaim"
,"RH_M4sdgleotech"
,"RH_M4sdgleotech_wdl"
,"m8_carbine"
,"m8_carbine_pmc"
,"m8_carbineGL"
,"m8_compact"
,"m8_compact_pmc"
,"m8_holo_sd"
,"m8_SAW"
,"RH_XM8"
,"RH_XM8C"
,"RH_XM8D"
,"RH_XM8DC"
,"RH_XM8DGL"
,"RH_XM8DSAW"
,"RH_XM8DSH"
,"RH_XM8GL"
,"RH_XM8SAW"
,"RH_XM8SH"
,"M16A2"
,"M16A2GL"
,"m16a4"
,"m16a4_acg"
,"M16A4_ACG_GL"
,"M16A4_GL"
,"RH_M16a1"
,"RH_M16a1gl"
,"RH_M16a1s"
,"RH_M16a1sgl"
,"RH_m16a2"
,"RH_m16a2aim"
,"RH_M16a2gl"
,"RH_M16a2glaim"
,"RH_M16a2s"
,"RH_M16a2sgl"
,"RH_M16a3"
,"RH_M16a3aim"
,"RH_M16a3c"
,"RH_M16a3cs"
,"RH_M16a3gl"
,"RH_M16a3s"
,"RH_M16a3sgl"
,"RH_M16a4"
,"RH_M16A4acog"
,"RH_M16A4aim"
,"RH_M16A4eotech"
,"RH_M16a4gl"
,"RH_M16A4glacog"
,"RH_M16A4glaim"
,"RH_M16A4gleotech"
,"RH_mas"
,"RH_masacog"
,"RH_masaim"
,"RH_masb"
,"RH_masbacog"
,"RH_masbaim"
,"RH_masbeotech"
,"RH_masbsd"
,"RH_masbsdacog"
,"RH_masbsdaim"
,"RH_masbsdeotech"
,"RH_maseotech"
,"RH_massd"
,"RH_massdacog"
,"RH_massdaim"
,"RH_massdeotech"
,"FN_FAL"
,"LeeEnfield"
,"RH_star21"
,"RH_an94"
,"RH_an94gl"
,"RH_ar10"
,"RH_ar10s"
,"RH_asval"
,"RH_asvalk"
,"RH_ctar21"
,"RH_ctar21glacog"
,"RH_ctar21m"
,"RH_ctar21mgl"
,"RH_Mk18"
,"RH_Mk18acog"
,"RH_Mk18aim"
,"RH_Mk18d"
,"RH_Mk18dacog"
,"RH_Mk18daim"
,"RH_mk18dc"
,"RH_mk18dcacog"
,"RH_mk18dcaim"
,"RH_mk18dceot"
,"RH_mk18dcgl"
,"RH_mk18dcglacog"
,"RH_mk18dcglaim"
,"RH_mk18dcgleot"
,"RH_mk18dcsd"
,"RH_mk18dcsdacog"
,"RH_mk18dcsdaim"
,"RH_mk18dcsdeot"
,"RH_Mk18deot"
,"RH_Mk18dgl"
,"RH_Mk18dglacog"
,"RH_Mk18dglaim"
,"RH_Mk18dgleot"
,"RH_Mk18dsd"
,"RH_Mk18dsdacog"
,"RH_Mk18dsdaim"
,"RH_Mk18dsdeot"
,"RH_Mk18eot"
,"RH_Mk18gl"
,"RH_Mk18glacog"
,"RH_Mk18glaim"
,"RH_Mk18gleot"
,"RH_Mk18sd"
,"RH_Mk18sdacog"
,"RH_Mk18sdaim"
,"RH_Mk18sdeot"
,"RH_Mk18t"
,"LEXX_SCAR_H_CQC_CCO_BLACK"
,"LEXX_SCAR_H_CQC_CCO_SD_BLACK"
,"LEXX_SCAR_H_STD_EGLM_Spect_BLACK"
,"LEXX_SCAR_L_CQC_BLACK"
,"LEXX_SCAR_L_CQC_CCO_SD_BLACK"
,"LEXX_SCAR_L_CQC_EGLM_Holo_BLACK"
,"LEXX_SCAR_L_CQC_Holo_BLACK"
,"LEXX_SCAR_L_STD_EGLM_RCO_BLACK"
,"LEXX_SCAR_L_STD_HOLO_BLACK"
,"LEXX_SCAR_L_STD_Mk4CQT_BLACK"
,"mcno_SCAR_H_CQC_CCO_SD_WHITE"
,"mcno_SCAR_H_CQC_CCO_WHITE"
,"mcno_SCAR_H_STD_EGLM_Spect_WHITE"
,"mcno_SCAR_L_CQC_CCO_SD_WHITE"
,"mcno_SCAR_L_CQC_EGLM_Holo_WHITE"
,"mcno_SCAR_L_CQC_Holo_WHITE"
,"mcno_SCAR_L_CQC_WHITE"
,"mcno_SCAR_L_STD_EGLM_RCO_WHITE"
,"mcno_SCAR_L_STD_HOLO_WHITE"
,"mcno_SCAR_L_STD_Mk4CQT_WHITE"
,"RH_SCARAK"
,"RH_SCARAKACOG"
,"RH_SCARAKAIM"
,"RH_SCARAKBAIM"
,"RH_SCARAKEOTECH"
,"RH_SCARH"
,"RH_SCARH_ACOG"
,"RH_SCARH_AIM"
,"RH_SCARH_EOTECH"
,"RH_SCARH_GL"
,"RH_SCARH_GL_ACOG"
,"RH_SCARH_GL_AIM"
,"RH_SCARH_GL_EOTECH"
,"RH_SCARH_GL_SPECTERDR"
,"RH_SCARH_MK4"
,"RH_SCARH_SD_ACOG"
,"RH_SCARH_SD_AIM"
,"RH_SCARH_SD_EOTECH"
,"RH_SCARH_SD_GL_AIM"
,"RH_SCARH_SD_GL_EOTECH"
,"RH_SCARH_SPECTERDR"
,"RH_SCARHB_EOTECH"
,"RH_SCARHB_GL_ACOG"
,"RH_SCARHB_SD_AIM"
,"RH_SCARHB_SD_GL_EOTECH"
,"RH_SCARL"
,"RH_SCARL_ACOG"
,"RH_SCARL_AIM"
,"RH_SCARL_DOC"
,"RH_SCARL_EOTECH"
,"RH_SCARL_GL"
,"RH_SCARL_GL_ACOG"
,"RH_SCARL_GL_AIM"
,"RH_SCARL_GL_EOTECH"
,"RH_SCARL_MK4"
,"RH_SCARL_SD_ACOG"
,"RH_SCARL_SD_AIM"
,"RH_SCARL_SD_DOC"
,"RH_SCARL_SD_EOTECH"
,"RH_SCARL_SD_GL_ACOG"
,"RH_SCARL_SD_GL_AIM"
,"RH_SCARL_SD_GL_EOTECH"
,"RH_SCARLB_AIM"
,"RH_SCARLB_GL_ACOG"
,"RH_SCARLB_SD_EOTECH"
,"RH_SCARLB_SD_GL_AIM"
,"SCAR_H_CQC_CCO"
,"SCAR_H_CQC_CCO_SD"
,"SCAR_H_STD_EGLM_Spect"
,"SCAR_L_CQC"
,"SCAR_L_CQC_CCO_SD"
,"SCAR_L_CQC_EGLM_Holo"
,"SCAR_L_CQC_Holo"
,"SCAR_L_STD_EGLM_RCO"
,"SCAR_L_STD_HOLO"
,"SCAR_L_STD_Mk4CQT"
,"RH_p90sdaim"
,"RH_p90sdeot"
,"RH_p90isd"
,"RH_mp5sd6aim"
,"RH_mp5sd6g"
,"RH_mp5sd6eot"
,"RH_mp5sd6RFX"
,"RH_mp7sdaim"
,"RH_mp7sdeot"
,"RH_umpsdaim"
,"RH_umpsdeot"
,"RH_umpsdRFX"
,"MP5SD"
,"RH_krisssdaim"
,"RH_krisssdeot"
,"RH_krisssdRFX"
,"RH_tmpsdaim"
,"RH_P90sd"
,"RH_mp5sd6"
,"RH_mp7sd"
,"RH_umpsd"
,"RH_krisssd"
,"RH_tmpsd"
,"RH_tmpsdeot"
,"RH_uzisd"
,"bizon_silenced"
,"RH_bizonsd"
,"RH_bizonsdk"
,"RH_P90aim"
,"RH_P90eot"
,"RH_P90i"
,"RH_HK53aim"
,"RH_HK53eot"
,"RH_HK53RFX"
,"RH_mp5a4aim"
,"RH_mp5a4eot"
,"RH_mp5a4RFX"
,"RH_mp5a5"
,"RH_mp5a5aim"
,"RH_mp5a5eodaim"
,"RH_mp5a5eodeot"
,"RH_mp5a5eodRFX"
,"RH_mp5a5eot"
,"RH_mp5a5eod"
,"RH_mp5a5RFX"
,"RH_mp5a5ris"
,"RH_mp5a5risaim"
,"RH_mp5a5riseot"
,"RH_mp5a5risRFX"
,"RH_mp5k"
,"RH_mp5kpdw"
,"RH_mp5kpdwaim"
,"RH_mp5kpdweot"
,"RH_mp5kpdwRFX"
,"RH_mp7aim"
,"RH_mp7eot"
,"RH_umpaim"
,"RH_umpRFX"
,"RH_bizon"
,"RH_bizonk"
,"bizon"
,"RH_P90"
,"RH_HK53"
,"RH_mp5a4"
,"RH_mp7"
,"RH_UMP"
,"RH_umpeot"
,"RH_mac10"
,"RH_PDR"
,"RH_pdraim"
,"RH_pdreot"
,"RH_PDW_AIM"
,"RH_PDW_EOTECH"
,"RH_krissaim"
,"RH_krisseot"
,"RH_krissRFX"
,"RH_tmpeot"
,"RH_uzig"
,"RH_uzim"
,"RH_pp2000"
,"RH_pp2000eot"
,"RH_PDW"
,"RH_PDW_ACOG"
,"RH_fmg9"
,"MP5A5"
,"RH_pp2000aim"
,"RH_tmp"
,"RH_kriss"
,"RH_tmpaim"
,"RH_uzi"
,"MIDF_Aug_A3"
,"MIDF_Aug_A3_acog"
,"MIDF_Aug_A3_acog_black"
,"MIDF_Aug_A3_acog_blue"
,"MIDF_Aug_A3_ACOG_GL"
,"MIDF_Aug_A3_ACOG_GL_BLACK"
,"MIDF_Aug_A3_ACOG_GL_BLUE"
,"MIDF_Aug_A3_Black"
,"MIDF_Aug_A3_Blue"
,"MIDF_Aug_A3_eotech"
,"MIDF_Aug_A3_eotech_black"
,"MIDF_Aug_A3_eotech_blue"
,"MIDF_Aug_A3_EOTECH_GL"
,"MIDF_Aug_A3_EOTECH_GL_BLACK"
,"MIDF_Aug_A3_EOTECH_GL_BLUE"
,"MIDF_Aug_A3_GL"
,"MIDF_Aug_A3_GL_black"
,"MIDF_Aug_A3_GL_blue"
,"M14_EP1"
,"RH_gr1"
,"RH_gr1sd"
,"RH_m14"
,"RH_m14acog"
,"RH_m14aim"
,"RH_M14EBR"
,"RH_M14EBR_SD"
,"RH_m14eot"
,"RH_m1s"
,"RH_m1sacog"
,"RH_m1saim"
,"RH_m1seot"
,"RH_m1sshd"
,"RH_m1st"
,"RH_m1stacog"
,"RH_m1staim"
,"RH_m1steot"
,"RH_m1stshd"
,"RH_m39emr"
,"RH_MK14"
,"RH_MK14ACOG"
,"RH_MK14AIM"
,"RH_mk14ebr"
,"RH_mk14ebr_sd"
,"RH_mk14ebrgc"
,"RH_mk14ebrgc_sd"
,"RH_MK14EOTECH"
,"RH_MK14SD"
,"RH_MK14SDACOG"
,"RH_MK14SDAIM"
,"RH_MK14SDEOTECH"
,"RH_mk14t"
,"RH_mk14tacog"
,"RH_mk14taim"
,"RH_mk14teot"
,"RH_mk14tsd"
,"RH_mk14tsdacog"
,"RH_mk14tsdaim"
,"RH_mk14tsdeot"
,"RH_oc14"
,"RH_oc14gl"
,"RH_oc14sd"
,"RH_sc2"
,"RH_sc2acog"
,"RH_sc2aim"
,"RH_sc2eot"
,"RH_sc2shd"
,"UKF_L115A3_fgrip"
,"UKF_L115A3_des"
,"UKF_L115A3_wdl_fgrip"
,"BAF_LRR_scoped"
,"UKF_L115A3_sd_fgrip"
,"UKF_L115A3_sd"
,"UKF_L115A3_sd_des"
,"UKF_L115A3_sd_des_fgrip"
,"UKF_L115A3_sd_wdl"
,"BAF_AS50_scoped_DZ"
,"BAF_LRR_scoped_W"
,"UKF_L115A3"
,"UKF_L115A3_des_fgrip"
,"UKF_L115A3_wdl"
,"UKF_L115A3_sd_wdl_fgrip"
,"m107_SKN"
,"USSR_cheytacM200_FDZ"
,"USSR_cheytacM200_sd_FDZ"
,"KSVK_DZE"
,"LEXX_SCAR_H_LNG_Sniper_SD_BLACK"
,"mcno_SCAR_H_LNG_Sniper_SD_WHITE"
,"RH_asvalsp"
,"RH_gr1sdsp"
,"RH_oc14sdsp"
,"RH_hk417sdsp"
,"RH_M14EBRSP_SD"
,"RH_MK21A5SD"
,"RH_MK12sd"
,"RH_MK12mod1sd"
,"RH_mk14ebrsp_sd"
,"SCAR_H_LNG_Sniper_SD"
,"VSS_vintorez"
,"RH_ak105sp"
,"RH_ak105glsp"
,"RH_AK107sp"
,"RH_AK107glsp"
,"RH_ak74sp"
,"RH_ak74msp"
,"RH_ak74mglsp"
,"RH_aks74sp"
,"RH_aks74msp"
,"RH_aks74mglsp"
,"RH_aks74psp"
,"RH_aks74pglsp"
,"RH_oc14glsp"
,"SVD_des_EP1"
,"RH_SVDb"
,"SVD_CAMO"
,"SVD"
,"RH_SVDg"
,"SVD_NSPU_EP1"
,"RH_SVDs"
,"RH_SVU"
,"RH_ak104sp"
,"FN_FAL_ANPVS4"
,"RH_gr1sp"
,"RH_oc14sp"
,"RH_hk417sp"
,"RH_SVD"
,"RH_sc2sp"
,"SCAR_H_LNG_Sniper"
,"mcno_SCAR_H_LNG_Sniper_WHITE"
,"LEXX_SCAR_H_LNG_Sniper_BLACK"
,"MCNO_M110_NVG_EP1_WHITE"
,"LEXX_M110_NVG_EP1_BLACK"
,"M110_NVG_EP1"
,"RH_M14EBRSP"
,"RH_m1ssp"
,"RH_MK12"
,"RH_MK12mod1"
,"M4SPR"
,"RH_mk14ebrsp"
,"RH_aks74uptsp"
,"RH_ak104glsp"
,"RH_ak103glsp"
,"AKS_74_NSPU"
,"RH_m1stsp"
,"RH_MK21A5"
,"M24"
,"M24_des_EP1"
,"RH_m21"
,"M40A3"
,"RH_M40A3"
,"RH_M40A5"
,"DMR_SKN"
,"RH_ak103sp"
,"RH_akmsp"
,"huntingrifle"
,"RH_M40A1"
,"m8_sharpshooter"
,"RH_M14EBRGC_SD"
,"RH_M14EBRGC"
,"BAF_L110A1_Aim_FDZ"
,"BAF_L7A2_GPMG_FDZ"
,"M240_FDZ"
,"m240_scoped_EP1_DZE"
,"M249_FDZ"
,"M249_EP1_DZ"
,"M249_m145_EP1_DZE"
,"M60A4_EP1_DZE"
,"Mcno_M249_m145_EP1_white_FDZ"
,"MG36_FDZ"
,"MG36_camo_FDZ"
,"Mk_48_DES_EP1_FDZ"
,"Mk_48_DZ"
,"Pecheneg_DZ"
,"PK_DZ"
,"RH_M249_FDZ"
,"RH_M249acog_FDZ"
,"RH_M249elcan_FDZ"
,"RH_M249p_FDZ"
,"RH_M249pacog_FDZ"
,"RH_M249pelcan_FDZ"
,"RH_M60E4_FDZ"
,"RH_M60E4_ACOG_FDZ"
,"RH_M60E4_ELCAN_FDZ"
,"RH_M60E4_EOTECH_FDZ"
,"RH_MK43_FDZ"
,"RH_MK43_ACOG_FDZ"
,"RH_MK43_ELCAN_FDZ"
,"RH_MK43_EOTECH_FDZ"
,"RH_Mk48mod1_FDZ"
,"RH_Mk48mod1acog_FDZ"
,"RH_Mk48mod1elcan_FDZ"
,"RH_rpk47_FDZ"
,"RH_rpk74_FDZ"
,"RH_rpk74m_FDZ"
,"RPK_74_FDZ"
,"RPK_74_Large_FDZ"
,"ukf_gpmg_FDZ"
,"ukf_gpmg_fgrip_FDZ"
,"ukf_L86A2LSW_FDZ"
,"ukf_L86A2LSW_fgrip_FDZ"
,"ukf_L86A2LSW_susat_FDZ"
,"ukf_L86A2LSW_susat_fgrip_FDZ"
,"ukf_lmg_FDZ"
,"ukf_lmg_ACOG_FDZ"
,"ukf_lmg_ACOG_fgrip_FDZ"
,"ukf_lmg_fgrip_FDZ"
,"ukf_lmg_SUSAT_FDZ"
,"ukf_lmg_SUSAT_fgrip_FDZ"]; //Weapongrade 2 rifles
DZAI_Rifles3 = ["Winchester1866"
,"AA12_PMC"
,"MR43"
,"M1014"
,"Remington870"
,"Remington870_lamp"
,"Saiga12K"
,"RH_acr"
,"RH_acracog"
,"RH_acraim"
,"RH_acrb"
,"RH_acrbacog"
,"RH_acrbaim"
,"RH_acrbeotech"
,"RH_acrbgl"
,"RH_acrbglacog"
,"RH_acrbglaim"
,"RH_acrbgleotech"
,"RH_acreotech"
,"RH_acrgl"
,"RH_acrglacog"
,"RH_acrglaim"
,"RH_acrgleotech"
,"RH_hk416"
,"RH_hk416acog"
,"RH_hk416aim"
,"RH_hk416eotech"
,"RH_hk416gl"
,"RH_hk416glacog"
,"RH_hk416glaim"
,"RH_hk416gleotech"
,"RH_hk416s"
,"RH_hk416sacog"
,"RH_hk416saim"
,"RH_hk416sd"
,"RH_hk416sdaim"
,"RH_hk416sdeotech"
,"RH_hk416sdgl"
,"RH_hk416sdglaim"
,"RH_hk416sdgleotech"
,"RH_hk416seotech"
,"RH_hk416sgl"
,"RH_hk416sglacog"
,"RH_hk416sglaim"
,"RH_hk416sgleotech"
,"RH_hk417"
,"RH_hk417acog"
,"RH_hk417aim"
,"RH_hk417eotech"
,"RH_hk417s"
,"RH_hk417sacog"
,"RH_hk417saim"
,"RH_hk417sd"
,"RH_hk417sdacog"
,"RH_hk417sdaim"
,"RH_hk417sdeotech"
,"RH_hk417seotech"
,"RH_hk417sgl"
,"RH_hk417sglacog"
,"RH_hk417sglaim"
,"RH_hk417sgleotech"
,"G36_C_SD_camo"
,"G36_C_SD_eotech"
,"G36a"
,"G36A_camo"
,"G36C"
,"G36C_camo"
,"G36K"
,"G36K_camo"
,"AK_107_GL_kobra"
,"AK_107_GL_pso"
,"AK_107_kobra"
,"AK_107_pso"
,"AK_47_M"
,"AK_47_S"
,"AK_74"
,"AK_74_GL"
,"AK_74_GL_kobra"
,"AKS_74"
,"AKS_74_kobra"
,"AKS_74_pso"
,"AKS_74_U"
,"AKS_74_UN_kobra"
,"AKS_GOLD"
,"RH_AK102"
,"RH_AK102GL"
,"RH_ak103"
,"RH_ak103gl"
,"RH_ak103k"
,"RH_ak103kgl"
,"RH_ak104"
,"RH_ak104_1p29"
,"RH_ak104gl"
,"RH_ak104k"
,"RH_ak104kgl"
,"RH_ak105"
,"RH_ak105gl"
,"RH_ak105k"
,"RH_ak105kgl"
,"RH_AK107"
,"RH_AK107gl"
,"RH_AK107k"
,"RH_AK107kgl"
,"RH_ak47"
,"RH_ak47gl"
,"RH_ak74"
,"RH_ak74gl"
,"RH_ak74k"
,"RH_ak74kgl"
,"RH_ak74m"
,"RH_ak74mgl"
,"RH_ak74mk"
,"RH_ak74mkgl"
,"RH_akm"
,"RH_akmgl"
,"RH_akms"
,"RH_akmssd"
,"RH_aks47"
,"RH_aks47b"
,"RH_aks47g"
,"RH_aks47s"
,"RH_aks74"
,"RH_aks74gl"
,"RH_aks74k"
,"RH_aks74kgl"
,"RH_aks74m"
,"RH_aks74mgl"
,"RH_aks74mgl1p29"
,"RH_aks74mk"
,"RH_aks74mkgl"
,"RH_aks74p"
,"RH_aks74pgl"
,"RH_aks74pk"
,"RH_aks74pkgl"
,"RH_aks74u"
,"RH_aks74uk"
,"RH_aks74upt"
,"RH_aks74uptk"
,"RH_aks74usd"
,"RH_aks74usdk"
,"RH_rk95"
,"RH_Rk95ag"
,"RH_Rk95aim"
,"RH_Rk95sd"
,"RH_Rk95sdag"
,"RH_Rk95sdaim"
,"Sa58P_EP1"
,"Sa58V_CCO_EP1"
,"Sa58V_EP1"
,"Sa58V_RCO_EP1"
,"BAF_L85A2_RIS_ACOG"
,"BAF_L85A2_RIS_CWS"
,"BAF_L85A2_RIS_Holo"
,"BAF_L85A2_RIS_SUSAT"
,"BAF_L85A2_UGL_ACOG"
,"BAF_L85A2_UGL_Holo"
,"BAF_L85A2_UGL_SUSAT"
,"ukf_L85A2"
,"ukf_L85A2_acog"
,"ukf_L85A2_acog_CQB"
,"ukf_L85A2_RIS"
,"ukf_L85A2_sd"
,"ukf_L85A2_sd_CQB"
,"ukf_L85A2_susat"
,"ukf_L85A2AG36"
,"ukf_L85A2AG36_acog"
,"ukf_L85A2AG36_acog_CQB"
,"ukf_L85A2AG36_acog_fgrip"
,"ukf_L85A2AG36_acog_fgrip_CQB"
,"ukf_L85A2AG36_fgrip"
,"ukf_L85A2AG36_sd"
,"ukf_L85A2AG36_sd_CQB"
,"ukf_L85A2AG36_sd_fgrip"
,"ukf_L85A2AG36_sd_fgrip_CQB"
,"ukf_L85A2AG36_susat"
,"ukf_L85A2AG36_susat_fgrip"
,"ukf_L85A2K_susat"
,"ukf_L86A2LSW"
,"ukf_L86A2LSW_fgrip"
,"ukf_L86A2LSW_susat"
,"ukf_L86A2LSW_susat_fgrip"
,"M4A1"
,"M4A1_Aim"
,"M4A1_Aim_camo"
,"M4A1_AIM_SD_camo"
,"M4A1_HWS_GL"
,"M4A1_HWS_GL_camo"
,"M4A1_HWS_GL_SD_Camo"
,"M4A1_RCO_GL"
,"M4A3_CCO_EP1"
,"M4A3_RCO_GL_EP1"
,"RH_M4"
,"RH_M4a1"
,"RH_M4a1acog"
,"RH_M4a1aim"
,"RH_M4a1eotech"
,"RH_M4a1gl"
,"RH_M4a1glacog"
,"RH_M4a1glaim"
,"RH_M4a1gleotech"
,"RH_M4a1r"
,"RH_M4acog"
,"RH_M4aim"
,"RH_M4aim_wdl"
,"RH_M4C"
,"RH_M4CACOG"
,"RH_M4CAIM"
,"RH_M4CEOTECH"
,"RH_M4CGL"
,"RH_M4CGLACOG"
,"RH_M4CGLAIM"
,"RH_M4CGLEOTECH"
,"RH_M4CMK"
,"RH_M4CMKACOG"
,"RH_M4CMKAIM"
,"RH_M4CMKEOTECH"
,"RH_M4CS"
,"RH_M4CSACOG"
,"RH_M4CSAIM"
,"RH_M4CSEOTECH"
,"RH_M4CT"
,"RH_M4CT_F"
,"RH_M4CTSD"
,"RH_M4CTSD_F"
,"RH_M4CTSDACOG"
,"RH_M4CTSDACOG_F"
,"RH_M4CTSDAIM"
,"RH_M4CTSDAIM_F"
,"RH_M4CTSDEOTECH"
,"RH_M4CTSDEOTECH_F"
,"RH_M4CTSDGL"
,"RH_M4CTSDGL_F"
,"RH_M4CTSDGLACOG"
,"RH_M4CTSDGLACOG_F"
,"RH_M4CTSDGLAIM"
,"RH_M4CTSDGLAIM_F"
,"RH_M4CTSDGLEOTECH"
,"RH_M4CTSDGLEOTECH_F"
,"RH_M4eotech"
,"RH_M4gl"
,"RH_M4glacog"
,"RH_M4glaim"
,"RH_M4gleotech"
,"RH_M4gleotech_wdl"
,"RH_M4m"
,"RH_M4macog"
,"RH_M4maim"
,"RH_M4meotech"
,"RH_M4r"
,"RH_M4sbr"
,"RH_M4sbracog"
,"RH_M4sbraim"
,"RH_M4sbreotech"
,"RH_M4sd"
,"RH_M4sdacog"
,"RH_M4sdaim"
,"RH_M4sdaim_wdl"
,"RH_M4sdeotech"
,"RH_M4sdgl"
,"RH_M4sdglacog"
,"RH_M4sdglaim"
,"RH_M4sdgleotech"
,"RH_M4sdgleotech_wdl"
,"m8_carbine"
,"m8_carbine_pmc"
,"m8_carbineGL"
,"m8_compact"
,"m8_compact_pmc"
,"m8_holo_sd"
,"m8_SAW"
,"RH_XM8"
,"RH_XM8C"
,"RH_XM8D"
,"RH_XM8DC"
,"RH_XM8DGL"
,"RH_XM8DSAW"
,"RH_XM8DSH"
,"RH_XM8GL"
,"RH_XM8SAW"
,"RH_XM8SH"
,"M16A2"
,"M16A2GL"
,"m16a4"
,"m16a4_acg"
,"M16A4_ACG_GL"
,"M16A4_GL"
,"RH_M16a1"
,"RH_M16a1gl"
,"RH_M16a1s"
,"RH_M16a1sgl"
,"RH_m16a2"
,"RH_m16a2aim"
,"RH_M16a2gl"
,"RH_M16a2glaim"
,"RH_M16a2s"
,"RH_M16a2sgl"
,"RH_M16a3"
,"RH_M16a3aim"
,"RH_M16a3c"
,"RH_M16a3cs"
,"RH_M16a3gl"
,"RH_M16a3s"
,"RH_M16a3sgl"
,"RH_M16a4"
,"RH_M16A4acog"
,"RH_M16A4aim"
,"RH_M16A4eotech"
,"RH_M16a4gl"
,"RH_M16A4glacog"
,"RH_M16A4glaim"
,"RH_M16A4gleotech"
,"RH_mas"
,"RH_masacog"
,"RH_masaim"
,"RH_masb"
,"RH_masbacog"
,"RH_masbaim"
,"RH_masbeotech"
,"RH_masbsd"
,"RH_masbsdacog"
,"RH_masbsdaim"
,"RH_masbsdeotech"
,"RH_maseotech"
,"RH_massd"
,"RH_massdacog"
,"RH_massdaim"
,"RH_massdeotech"
,"FN_FAL"
,"LeeEnfield"
,"RH_star21"
,"RH_an94"
,"RH_an94gl"
,"RH_ar10"
,"RH_ar10s"
,"RH_asval"
,"RH_asvalk"
,"RH_ctar21"
,"RH_ctar21glacog"
,"RH_ctar21m"
,"RH_ctar21mgl"
,"RH_Mk18"
,"RH_Mk18acog"
,"RH_Mk18aim"
,"RH_Mk18d"
,"RH_Mk18dacog"
,"RH_Mk18daim"
,"RH_mk18dc"
,"RH_mk18dcacog"
,"RH_mk18dcaim"
,"RH_mk18dceot"
,"RH_mk18dcgl"
,"RH_mk18dcglacog"
,"RH_mk18dcglaim"
,"RH_mk18dcgleot"
,"RH_mk18dcsd"
,"RH_mk18dcsdacog"
,"RH_mk18dcsdaim"
,"RH_mk18dcsdeot"
,"RH_Mk18deot"
,"RH_Mk18dgl"
,"RH_Mk18dglacog"
,"RH_Mk18dglaim"
,"RH_Mk18dgleot"
,"RH_Mk18dsd"
,"RH_Mk18dsdacog"
,"RH_Mk18dsdaim"
,"RH_Mk18dsdeot"
,"RH_Mk18eot"
,"RH_Mk18gl"
,"RH_Mk18glacog"
,"RH_Mk18glaim"
,"RH_Mk18gleot"
,"RH_Mk18sd"
,"RH_Mk18sdacog"
,"RH_Mk18sdaim"
,"RH_Mk18sdeot"
,"RH_Mk18t"
,"LEXX_SCAR_H_CQC_CCO_BLACK"
,"LEXX_SCAR_H_CQC_CCO_SD_BLACK"
,"LEXX_SCAR_H_STD_EGLM_Spect_BLACK"
,"LEXX_SCAR_L_CQC_BLACK"
,"LEXX_SCAR_L_CQC_CCO_SD_BLACK"
,"LEXX_SCAR_L_CQC_EGLM_Holo_BLACK"
,"LEXX_SCAR_L_CQC_Holo_BLACK"
,"LEXX_SCAR_L_STD_EGLM_RCO_BLACK"
,"LEXX_SCAR_L_STD_HOLO_BLACK"
,"LEXX_SCAR_L_STD_Mk4CQT_BLACK"
,"mcno_SCAR_H_CQC_CCO_SD_WHITE"
,"mcno_SCAR_H_CQC_CCO_WHITE"
,"mcno_SCAR_H_STD_EGLM_Spect_WHITE"
,"mcno_SCAR_L_CQC_CCO_SD_WHITE"
,"mcno_SCAR_L_CQC_EGLM_Holo_WHITE"
,"mcno_SCAR_L_CQC_Holo_WHITE"
,"mcno_SCAR_L_CQC_WHITE"
,"mcno_SCAR_L_STD_EGLM_RCO_WHITE"
,"mcno_SCAR_L_STD_HOLO_WHITE"
,"mcno_SCAR_L_STD_Mk4CQT_WHITE"
,"RH_SCARAK"
,"RH_SCARAKACOG"
,"RH_SCARAKAIM"
,"RH_SCARAKBAIM"
,"RH_SCARAKEOTECH"
,"RH_SCARH"
,"RH_SCARH_ACOG"
,"RH_SCARH_AIM"
,"RH_SCARH_EOTECH"
,"RH_SCARH_GL"
,"RH_SCARH_GL_ACOG"
,"RH_SCARH_GL_AIM"
,"RH_SCARH_GL_EOTECH"
,"RH_SCARH_GL_SPECTERDR"
,"RH_SCARH_MK4"
,"RH_SCARH_SD_ACOG"
,"RH_SCARH_SD_AIM"
,"RH_SCARH_SD_EOTECH"
,"RH_SCARH_SD_GL_AIM"
,"RH_SCARH_SD_GL_EOTECH"
,"RH_SCARH_SPECTERDR"
,"RH_SCARHB_EOTECH"
,"RH_SCARHB_GL_ACOG"
,"RH_SCARHB_SD_AIM"
,"RH_SCARHB_SD_GL_EOTECH"
,"RH_SCARL"
,"RH_SCARL_ACOG"
,"RH_SCARL_AIM"
,"RH_SCARL_DOC"
,"RH_SCARL_EOTECH"
,"RH_SCARL_GL"
,"RH_SCARL_GL_ACOG"
,"RH_SCARL_GL_AIM"
,"RH_SCARL_GL_EOTECH"
,"RH_SCARL_MK4"
,"RH_SCARL_SD_ACOG"
,"RH_SCARL_SD_AIM"
,"RH_SCARL_SD_DOC"
,"RH_SCARL_SD_EOTECH"
,"RH_SCARL_SD_GL_ACOG"
,"RH_SCARL_SD_GL_AIM"
,"RH_SCARL_SD_GL_EOTECH"
,"RH_SCARLB_AIM"
,"RH_SCARLB_GL_ACOG"
,"RH_SCARLB_SD_EOTECH"
,"RH_SCARLB_SD_GL_AIM"
,"SCAR_H_CQC_CCO"
,"SCAR_H_CQC_CCO_SD"
,"SCAR_H_STD_EGLM_Spect"
,"SCAR_L_CQC"
,"SCAR_L_CQC_CCO_SD"
,"SCAR_L_CQC_EGLM_Holo"
,"SCAR_L_CQC_Holo"
,"SCAR_L_STD_EGLM_RCO"
,"SCAR_L_STD_HOLO"
,"SCAR_L_STD_Mk4CQT"
,"RH_p90sdaim"
,"RH_p90sdeot"
,"RH_p90isd"
,"RH_mp5sd6aim"
,"RH_mp5sd6g"
,"RH_mp5sd6eot"
,"RH_mp5sd6RFX"
,"RH_mp7sdaim"
,"RH_mp7sdeot"
,"RH_umpsdaim"
,"RH_umpsdeot"
,"RH_umpsdRFX"
,"MP5SD"
,"RH_krisssdaim"
,"RH_krisssdeot"
,"RH_krisssdRFX"
,"RH_tmpsdaim"
,"RH_P90sd"
,"RH_mp5sd6"
,"RH_mp7sd"
,"RH_umpsd"
,"RH_krisssd"
,"RH_tmpsd"
,"RH_tmpsdeot"
,"RH_uzisd"
,"bizon_silenced"
,"RH_bizonsd"
,"RH_bizonsdk"
,"RH_P90aim"
,"RH_P90eot"
,"RH_P90i"
,"RH_HK53aim"
,"RH_HK53eot"
,"RH_HK53RFX"
,"RH_mp5a4aim"
,"RH_mp5a4eot"
,"RH_mp5a4RFX"
,"RH_mp5a5"
,"RH_mp5a5aim"
,"RH_mp5a5eodaim"
,"RH_mp5a5eodeot"
,"RH_mp5a5eodRFX"
,"RH_mp5a5eot"
,"RH_mp5a5eod"
,"RH_mp5a5RFX"
,"RH_mp5a5ris"
,"RH_mp5a5risaim"
,"RH_mp5a5riseot"
,"RH_mp5a5risRFX"
,"RH_mp5k"
,"RH_mp5kpdw"
,"RH_mp5kpdwaim"
,"RH_mp5kpdweot"
,"RH_mp5kpdwRFX"
,"RH_mp7aim"
,"RH_mp7eot"
,"RH_umpaim"
,"RH_umpRFX"
,"RH_bizon"
,"RH_bizonk"
,"bizon"
,"RH_P90"
,"RH_HK53"
,"RH_mp5a4"
,"RH_mp7"
,"RH_UMP"
,"RH_umpeot"
,"RH_mac10"
,"RH_PDR"
,"RH_pdraim"
,"RH_pdreot"
,"RH_PDW_AIM"
,"RH_PDW_EOTECH"
,"RH_krissaim"
,"RH_krisseot"
,"RH_krissRFX"
,"RH_tmpeot"
,"RH_uzig"
,"RH_uzim"
,"RH_pp2000"
,"RH_pp2000eot"
,"RH_PDW"
,"RH_PDW_ACOG"
,"RH_fmg9"
,"MP5A5"
,"RH_pp2000aim"
,"RH_tmp"
,"RH_kriss"
,"RH_tmpaim"
,"RH_uzi"
,"MIDF_Aug_A3"
,"MIDF_Aug_A3_acog"
,"MIDF_Aug_A3_acog_black"
,"MIDF_Aug_A3_acog_blue"
,"MIDF_Aug_A3_ACOG_GL"
,"MIDF_Aug_A3_ACOG_GL_BLACK"
,"MIDF_Aug_A3_ACOG_GL_BLUE"
,"MIDF_Aug_A3_Black"
,"MIDF_Aug_A3_Blue"
,"MIDF_Aug_A3_eotech"
,"MIDF_Aug_A3_eotech_black"
,"MIDF_Aug_A3_eotech_blue"
,"MIDF_Aug_A3_EOTECH_GL"
,"MIDF_Aug_A3_EOTECH_GL_BLACK"
,"MIDF_Aug_A3_EOTECH_GL_BLUE"
,"MIDF_Aug_A3_GL"
,"MIDF_Aug_A3_GL_black"
,"MIDF_Aug_A3_GL_blue"
,"M14_EP1"
,"RH_gr1"
,"RH_gr1sd"
,"RH_m14"
,"RH_m14acog"
,"RH_m14aim"
,"RH_M14EBR"
,"RH_M14EBR_SD"
,"RH_m14eot"
,"RH_m1s"
,"RH_m1sacog"
,"RH_m1saim"
,"RH_m1seot"
,"RH_m1sshd"
,"RH_m1st"
,"RH_m1stacog"
,"RH_m1staim"
,"RH_m1steot"
,"RH_m1stshd"
,"RH_m39emr"
,"RH_MK14"
,"RH_MK14ACOG"
,"RH_MK14AIM"
,"RH_mk14ebr"
,"RH_mk14ebr_sd"
,"RH_mk14ebrgc"
,"RH_mk14ebrgc_sd"
,"RH_MK14EOTECH"
,"RH_MK14SD"
,"RH_MK14SDACOG"
,"RH_MK14SDAIM"
,"RH_MK14SDEOTECH"
,"RH_mk14t"
,"RH_mk14tacog"
,"RH_mk14taim"
,"RH_mk14teot"
,"RH_mk14tsd"
,"RH_mk14tsdacog"
,"RH_mk14tsdaim"
,"RH_mk14tsdeot"
,"RH_oc14"
,"RH_oc14gl"
,"RH_oc14sd"
,"RH_sc2"
,"RH_sc2acog"
,"RH_sc2aim"
,"RH_sc2eot"
,"RH_sc2shd"
,"UKF_L115A3_fgrip"
,"UKF_L115A3_des"
,"UKF_L115A3_wdl_fgrip"
,"BAF_LRR_scoped"
,"UKF_L115A3_sd_fgrip"
,"UKF_L115A3_sd"
,"UKF_L115A3_sd_des"
,"UKF_L115A3_sd_des_fgrip"
,"UKF_L115A3_sd_wdl"
,"BAF_AS50_scoped_DZ"
,"BAF_LRR_scoped_W"
,"UKF_L115A3"
,"UKF_L115A3_des_fgrip"
,"UKF_L115A3_wdl"
,"UKF_L115A3_sd_wdl_fgrip"
,"m107_SKN"
,"USSR_cheytacM200_FDZ"
,"USSR_cheytacM200_sd_FDZ"
,"KSVK_DZE"
,"LEXX_SCAR_H_LNG_Sniper_SD_BLACK"
,"mcno_SCAR_H_LNG_Sniper_SD_WHITE"
,"RH_asvalsp"
,"RH_gr1sdsp"
,"RH_oc14sdsp"
,"RH_hk417sdsp"
,"RH_M14EBRSP_SD"
,"RH_MK21A5SD"
,"RH_MK12sd"
,"RH_MK12mod1sd"
,"RH_mk14ebrsp_sd"
,"SCAR_H_LNG_Sniper_SD"
,"VSS_vintorez"
,"RH_ak105sp"
,"RH_ak105glsp"
,"RH_AK107sp"
,"RH_AK107glsp"
,"RH_ak74sp"
,"RH_ak74msp"
,"RH_ak74mglsp"
,"RH_aks74sp"
,"RH_aks74msp"
,"RH_aks74mglsp"
,"RH_aks74psp"
,"RH_aks74pglsp"
,"RH_oc14glsp"
,"SVD_des_EP1"
,"RH_SVDb"
,"SVD_CAMO"
,"SVD"
,"RH_SVDg"
,"SVD_NSPU_EP1"
,"RH_SVDs"
,"RH_SVU"
,"RH_ak104sp"
,"FN_FAL_ANPVS4"
,"RH_gr1sp"
,"RH_oc14sp"
,"RH_hk417sp"
,"RH_SVD"
,"RH_sc2sp"
,"SCAR_H_LNG_Sniper"
,"mcno_SCAR_H_LNG_Sniper_WHITE"
,"LEXX_SCAR_H_LNG_Sniper_BLACK"
,"MCNO_M110_NVG_EP1_WHITE"
,"LEXX_M110_NVG_EP1_BLACK"
,"M110_NVG_EP1"
,"RH_M14EBRSP"
,"RH_m1ssp"
,"RH_MK12"
,"RH_MK12mod1"
,"M4SPR"
,"RH_mk14ebrsp"
,"RH_aks74uptsp"
,"RH_ak104glsp"
,"RH_ak103glsp"
,"AKS_74_NSPU"
,"RH_m1stsp"
,"RH_MK21A5"
,"M24"
,"M24_des_EP1"
,"RH_m21"
,"M40A3"
,"RH_M40A3"
,"RH_M40A5"
,"DMR_SKN"
,"RH_ak103sp"
,"RH_akmsp"
,"huntingrifle"
,"RH_M40A1"
,"m8_sharpshooter"
,"RH_M14EBRGC_SD"
,"RH_M14EBRGC"
,"BAF_L110A1_Aim_FDZ"
,"BAF_L7A2_GPMG_FDZ"
,"M240_FDZ"
,"m240_scoped_EP1_DZE"
,"M249_FDZ"
,"M249_EP1_DZ"
,"M249_m145_EP1_DZE"
,"M60A4_EP1_DZE"
,"Mcno_M249_m145_EP1_white_FDZ"
,"MG36_FDZ"
,"MG36_camo_FDZ"
,"Mk_48_DES_EP1_FDZ"
,"Mk_48_DZ"
,"Pecheneg_DZ"
,"PK_DZ"
,"RH_M249_FDZ"
,"RH_M249acog_FDZ"
,"RH_M249elcan_FDZ"
,"RH_M249p_FDZ"
,"RH_M249pacog_FDZ"
,"RH_M249pelcan_FDZ"
,"RH_M60E4_FDZ"
,"RH_M60E4_ACOG_FDZ"
,"RH_M60E4_ELCAN_FDZ"
,"RH_M60E4_EOTECH_FDZ"
,"RH_MK43_FDZ"
,"RH_MK43_ACOG_FDZ"
,"RH_MK43_ELCAN_FDZ"
,"RH_MK43_EOTECH_FDZ"
,"RH_Mk48mod1_FDZ"
,"RH_Mk48mod1acog_FDZ"
,"RH_Mk48mod1elcan_FDZ"
,"RH_rpk47_FDZ"
,"RH_rpk74_FDZ"
,"RH_rpk74m_FDZ"
,"RPK_74_FDZ"
,"RPK_74_Large_FDZ"
,"ukf_gpmg_FDZ"
,"ukf_gpmg_fgrip_FDZ"
,"ukf_L86A2LSW_FDZ"
,"ukf_L86A2LSW_fgrip_FDZ"
,"ukf_L86A2LSW_susat_FDZ"
,"ukf_L86A2LSW_susat_fgrip_FDZ"
,"ukf_lmg_FDZ"
,"ukf_lmg_ACOG_FDZ"
,"ukf_lmg_ACOG_fgrip_FDZ"
,"ukf_lmg_fgrip_FDZ"
,"ukf_lmg_SUSAT_FDZ"
,"ukf_lmg_SUSAT_fgrip_FDZ"]; //Weapongrade 3 rifles
	
/*
	Custom rifle tables can be defined below this line (DZAI_Rifles4 - DZAI_Rifles9) for the corresponding custom weapongrade level using the same format above. 
	Note: If a custom weapongrade is used without defining the corresponding custom rifle array, the DZAI_Rifles3 array will be used instead.
	Instructions: Replace "nil" with the wanted rifle array. Refer to the above rifle arrays for examples on how to define custom rifle tables.
	Custom rifle tables can only be used with custom-defined spawns (spawns created using the DZAI_spawn function). 
*/

//------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
DZAI_Rifles4 = nil; //weapongrade 4 weapons
DZAI_Rifles5 = nil; //weapongrade 5 weapons
DZAI_Rifles6 = nil; //weapongrade 6 weapons
DZAI_Rifles7 = nil; //weapongrade 7 weapons
DZAI_Rifles8 = nil; //weapongrade 8 weapons
DZAI_Rifles9 = nil; //weapongrade 9 weapons


//AI skin classnames. DZAI will use any of these classnames for AI spawned. Note: Additional skins may be included on a per-map or per-mod basis - see folders in \world_classname_configs
//------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
DZAI_BanditTypes = ["Taliban1","Taliban2","Taliban3","Taliban4","Taliban5","Taliban6","Taliban7","Taliban8","Taliban9","Taliban10","Taliban11","Taliban12","ETaliban1","ETaliban2","ETaliban3","ETaliban4","ETaliban5","ETaliban6","ETaliban7","ETaliban8","ETaliban9","ETaliban10","ETaliban11","ETaliban12","Terrorist1","Terrorist2","Terrorist3","Terrorist4","Terrorist5","Terrorist6","Terrorist7","Terrorist8","Terrorist9","Terrorist10","Terrorist11","Terrorist12","ETerrorist1","ETerrorist2","ETerrorist3","ETerrorist4","ETerrorist5","ETerrorist6","ETerrorist7","ETerrorist8","ETerrorist9","ETerrorist10","ETerrorist11","ETerrorist12"];


//AI Backpack types (for weapongrade levels 0-3)
//------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
DZAI_Backpacks0 = ["DZ_Patrol_Pack_EP1","DZ_Czech_Vest_Puch","DZ_Assault_Pack_EP1"];
DZAI_Backpacks1 = ["DZ_Patrol_Pack_EP1","DZ_Czech_Vest_Puch","DZ_Assault_Pack_EP1","DZ_British_ACU","DZ_TK_Assault_Pack_EP1","DZ_CivilBackpack_EP1","DZ_ALICE_Pack_EP1"];
DZAI_Backpacks2 = ["DZ_CivilBackpack_EP1","DZ_British_ACU","DZ_Backpack_EP1"];
DZAI_Backpacks3 = ["DZ_CivilBackpack_EP1","DZ_Backpack_EP1"];


//AI Food/Medical item types. DZAI_Edibles: Drinkable and edible items. DZAI_Medicals1: List of common medical items to be added to AI inventory. DZAI_Medicals2: List of all medical items available only in hospitals to be added to AI backpack.
//------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
DZAI_Edibles = ["ItemSodaCoke", "ItemSodaPepsi", "ItemWaterbottle", "FoodCanSardines", "FoodCanBakedBeans", "FoodCanFrankBeans", "FoodCanPasta", "ItemWaterbottleUnfilled","ItemWaterbottleBoiled","FoodmuttonCooked","FoodchickenCooked","FoodBaconCooked","FoodRabbitCooked","FoodbaconRaw","FoodchickenRaw","FoodmuttonRaw","foodrabbitRaw","FoodCanUnlabeled","FoodPistachio","FoodNutmix","FoodMRE"];
DZAI_Medicals1 = ["ItemBandage", "ItemPainkiller"];
DZAI_Medicals2 = ["ItemPainkiller", "ItemMorphine", "ItemBandage", "ItemBloodbag", "ItemAntibiotic","ItemEpinephrine"];


//AI Miscellaneous item types. DZAI_MiscItemS: List of random low-value items. DZAI_MiscItemL: List of random semi-valuable/useful items
//------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
DZAI_MiscItemS = ["ItemHeatpack", "HandRoadFlare", "HandChemBlue", "HandChemRed", "HandChemGreen","SmokeShell","TrashTinCan","TrashJackDaniels","ItemSodaEmpty"];
DZAI_MiscItemL = ["ItemJerrycan", "PartWheel", "PartEngine", "PartFueltank", "PartGlass", "PartVRotor","PartWoodPile"];


//AI toolbelt item types. Toolbelt items are added to AI inventory upon death. Format: [item classname, item probability]
//Weapongrade level 0-1 AI will use DZAI_tools0 table, weapongrade level 2-3 AI will use DZAI_tools1 table. Custom-spawned AI will use DZAI_tools1 table.
//NOTE: Do not delete any elements from this list, set its chance to zero intead. Only add elements to the end of the array, not in the middle.
//------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
DZAI_tools0 = [["ItemFlashlight",0.65],["ItemWatch",0.65],["ItemKnife",0.50],["ItemHatchet",0.40],["ItemCompass",0.40],["ItemMap",0.35],["ItemToolbox",0.15],["ItemMatchbox",0.15],["ItemFlashlightRed",0.05],["ItemGPS",0.005],["ItemRadio",0.005],["ItemCrowbar",0.15]];
DZAI_tools1 = [["ItemFlashlight",0.75],["ItemWatch",0.75],["ItemKnife",0.75],["ItemHatchet",0.70],["ItemCompass",0.75],["ItemMap",0.70],["ItemToolbox",0.35],["ItemMatchbox",0.40],["ItemFlashlightRed",0.10],["ItemGPS",0.10],["ItemRadio",0.075],["ItemCrowbar",0.35]];


//AI-useable toolbelt item types. These items are added to AI inventory at unit creation and may be used by AI. Format: [item classname, item probability]
//Weapongrade level 0-1 AI will use DZAI_gadgets0 table, weapongrade level 2-3 AI will use DZAI_gadgets1 table. Custom-spawned AI will use DZAI_gadgets1 table.
//------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
DZAI_gadgets0 = [["binocular",0.40],["NVGoggles",0.00]];
DZAI_gadgets1 = [["binocular",0.60],["NVGoggles",0.05]];



//NOTHING TO EDIT BEYOND THIS POINT

//Load custom DZAI settings file.
if ((!isNil "DZAI_overrideEnabled") && {DZAI_overrideEnabled}) then {call compile preprocessFileLineNumbers format ["%1\DZAI_settings_override.sqf",DZAI_directory]};

diag_log "[DZAI] DZAI configuration file loaded.";
